// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_cakerep_screen_init(void)
{
    ui_cakerep = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_cakerep, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_cakerep, lv_color_hex(0x454444), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cakerep, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_cakerep, lv_color_hex(0x6E6E6E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_cakerep, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_cakerep, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_cakerep, LV_BORDER_SIDE_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cake_recipe = lv_imgbtn_create(ui_cakerep);
    lv_imgbtn_set_src(ui_cake_recipe, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_kitchen_whisk_icon_png, NULL);
    lv_imgbtn_set_src(ui_cake_recipe, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_kitchen_whisk_icon_png, NULL);
    lv_imgbtn_set_src(ui_cake_recipe, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_cake_recipe, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_cake_recipe, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_cake_recipe, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_height(ui_cake_recipe, 72);
    lv_obj_set_width(ui_cake_recipe, LV_SIZE_CONTENT);   /// -137
    lv_obj_set_x(ui_cake_recipe, -340);
    lv_obj_set_y(ui_cake_recipe, -80);
    lv_obj_set_align(ui_cake_recipe, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_cake_recipe, lv_color_hex(0x6E6E6E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cake_recipe, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_cake_recipe, lv_color_hex(0x0F00FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_cake_recipe, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cake_home = lv_imgbtn_create(ui_cakerep);
    lv_imgbtn_set_src(ui_cake_home, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_home_icon_png, NULL);
    lv_imgbtn_set_src(ui_cake_home, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_home_icon_png, NULL);
    lv_imgbtn_set_src(ui_cake_home, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_cake_home, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_cake_home, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_cake_home, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_height(ui_cake_home, 79);
    lv_obj_set_width(ui_cake_home, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_cake_home, -347);
    lv_obj_set_y(ui_cake_home, -191);
    lv_obj_set_align(ui_cake_home, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_cake_home, lv_color_hex(0x6E6E6E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cake_home, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButton7 = lv_imgbtn_create(ui_cakerep);
    lv_imgbtn_set_src(ui_ImgButton7, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_cake_icon_png, NULL);
    lv_imgbtn_set_src(ui_ImgButton7, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_cake_icon_png, NULL);
    lv_imgbtn_set_src(ui_ImgButton7, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButton7, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButton7, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButton7, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_ImgButton7, 74);
    lv_obj_set_height(ui_ImgButton7, 74);
    lv_obj_set_x(ui_ImgButton7, -317);
    lv_obj_set_y(ui_ImgButton7, 25);
    lv_obj_set_align(ui_ImgButton7, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_ImgButton7, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ImgButton7, lv_color_hex(0xFFFC00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ImgButton7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ImgButton7, lv_color_hex(0xFFFC00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ImgButton7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ImgButton7, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ImgButton7, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_ImgButton7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_ImgButton7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_ImgButton7, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_ImgButton7, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cake_panel = lv_obj_create(ui_cakerep);
    lv_obj_set_width(ui_cake_panel, 696);
    lv_obj_set_height(ui_cake_panel, 482);
    lv_obj_set_x(ui_cake_panel, 59);
    lv_obj_set_y(ui_cake_panel, 11);
    lv_obj_set_align(ui_cake_panel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_cake_panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_cake_panel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_cake_panel, lv_color_hex(0xECE7D6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cake_panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_cake_panel, lv_color_hex(0xFFFC00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_cake_panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_cake_panel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_cake_panel, LV_BORDER_SIDE_TOP, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cakeflourlab = lv_label_create(ui_cake_panel);
    lv_obj_set_width(ui_cakeflourlab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_cakeflourlab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_cakeflourlab, -128);
    lv_obj_set_y(ui_cakeflourlab, -150);
    lv_obj_set_align(ui_cakeflourlab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_cakeflourlab, "FLOUR                 :");
    lv_obj_set_style_text_font(ui_cakeflourlab, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cakeflourtext = lv_textarea_create(ui_cake_panel);
    lv_obj_set_width(ui_cakeflourtext, 212);
    lv_obj_set_height(ui_cakeflourtext, 42);
    lv_obj_set_x(ui_cakeflourtext, 82);
    lv_obj_set_y(ui_cakeflourtext, -150);
    lv_obj_set_align(ui_cakeflourtext, LV_ALIGN_CENTER);
    if("0,1,2,3,4,5,6,7,8,9,." == "") lv_textarea_set_accepted_chars(ui_cakeflourtext, NULL);
    else lv_textarea_set_accepted_chars(ui_cakeflourtext, "0,1,2,3,4,5,6,7,8,9,.");
    lv_textarea_set_max_length(ui_cakeflourtext, 5);
    lv_textarea_set_text(ui_cakeflourtext, "437.5");
    lv_textarea_set_placeholder_text(ui_cakeflourtext, "Enter value in grams..");
    lv_obj_set_style_text_color(ui_cakeflourtext, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_cakeflourtext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_cakeflourtext, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_cakeflourtext, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_cakeflourtext, lv_color_hex(0xF6F583), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cakeflourtext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_cakeflourtext, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_cakeflourtext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_cakeflourtext, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_cakeflourtext, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_cakeflourtext, lv_color_hex(0x8C8C8C), LV_PART_MAIN | LV_STATE_EDITED);
    lv_obj_set_style_bg_opa(ui_cakeflourtext, 255, LV_PART_MAIN | LV_STATE_EDITED);
    lv_obj_set_style_text_color(ui_cakeflourtext, lv_color_hex(0x050505), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_cakeflourtext, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_color(ui_cakeflourtext, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_cakeflourtext, 255, LV_PART_MAIN | LV_STATE_FOCUSED);


    lv_obj_set_style_text_color(ui_cakeflourtext, lv_color_hex(0x000000), LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_cakeflourtext, 255, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_cakeflourtext, lv_color_hex(0x050505), LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_cakeflourtext, 255, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_FOCUSED);

    ui_cakesuglab = lv_label_create(ui_cake_panel);
    lv_obj_set_width(ui_cakesuglab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_cakesuglab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_cakesuglab, -128);
    lv_obj_set_y(ui_cakesuglab, -50);
    lv_obj_set_align(ui_cakesuglab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_cakesuglab, "SUGAR                 :");
    lv_obj_set_style_text_font(ui_cakesuglab, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cakeBPlab = lv_label_create(ui_cake_panel);
    lv_obj_set_width(ui_cakeBPlab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_cakeBPlab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_cakeBPlab, -155);
    lv_obj_set_y(ui_cakeBPlab, 50);
    lv_obj_set_align(ui_cakeBPlab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_cakeBPlab, "BAKING POWDER     :");
    lv_obj_set_style_text_font(ui_cakeBPlab, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cakesugtext = lv_textarea_create(ui_cake_panel);
    lv_obj_set_width(ui_cakesugtext, 212);
    lv_obj_set_height(ui_cakesugtext, 42);
    lv_obj_set_x(ui_cakesugtext, 82);
    lv_obj_set_y(ui_cakesugtext, -50);
    lv_obj_set_align(ui_cakesugtext, LV_ALIGN_CENTER);
    if("0,1,2,3,4,5,6,7,8,9,." == "") lv_textarea_set_accepted_chars(ui_cakesugtext, NULL);
    else lv_textarea_set_accepted_chars(ui_cakesugtext, "0,1,2,3,4,5,6,7,8,9,.");
    lv_textarea_set_max_length(ui_cakesugtext, 5);
    lv_textarea_set_text(ui_cakesugtext, "500");
    lv_textarea_set_placeholder_text(ui_cakesugtext, "Enter value in grams..");
    lv_obj_set_style_text_color(ui_cakesugtext, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_cakesugtext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_cakesugtext, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_cakesugtext, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_cakesugtext, lv_color_hex(0xF6F583), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cakesugtext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_cakesugtext, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_cakesugtext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_cakesugtext, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_cakesugtext, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_cakesugtext, lv_color_hex(0x030303), LV_PART_MAIN | LV_STATE_EDITED);
    lv_obj_set_style_text_opa(ui_cakesugtext, 255, LV_PART_MAIN | LV_STATE_EDITED);
    lv_obj_set_style_bg_color(ui_cakesugtext, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_cakesugtext, 255, LV_PART_MAIN | LV_STATE_FOCUSED);


    lv_obj_set_style_text_color(ui_cakesugtext, lv_color_hex(0x000000), LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_cakesugtext, 255, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_cakesugtext, lv_color_hex(0x000000), LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_cakesugtext, 255, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_FOCUSED);

    ui_cakeBPtext = lv_textarea_create(ui_cake_panel);
    lv_obj_set_width(ui_cakeBPtext, 212);
    lv_obj_set_height(ui_cakeBPtext, 42);
    lv_obj_set_x(ui_cakeBPtext, 83);
    lv_obj_set_y(ui_cakeBPtext, 50);
    lv_obj_set_align(ui_cakeBPtext, LV_ALIGN_CENTER);
    if("0,1,2,3,4,5,6,7,8,9,." == "") lv_textarea_set_accepted_chars(ui_cakeBPtext, NULL);
    else lv_textarea_set_accepted_chars(ui_cakeBPtext, "0,1,2,3,4,5,6,7,8,9,.");
    lv_textarea_set_max_length(ui_cakeBPtext, 5);
    lv_textarea_set_text(ui_cakeBPtext, "7.5");
    lv_textarea_set_placeholder_text(ui_cakeBPtext, "Enter value in grams..");
    lv_obj_set_style_text_color(ui_cakeBPtext, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_cakeBPtext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_cakeBPtext, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_cakeBPtext, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_cakeBPtext, lv_color_hex(0xF6F583), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cakeBPtext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_cakeBPtext, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_cakeBPtext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_cakeBPtext, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_cakeBPtext, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_cakeBPtext, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_cakeBPtext, 255, LV_PART_MAIN | LV_STATE_FOCUSED);


    lv_obj_set_style_text_color(ui_cakeBPtext, lv_color_hex(0x000000), LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_cakeBPtext, 255, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_cakeBPtext, lv_color_hex(0x000000), LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_cakeBPtext, 255, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_FOCUSED);

    ui_cakeCPlab = lv_label_create(ui_cake_panel);
    lv_obj_set_width(ui_cakeCPlab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_cakeCPlab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_cakeCPlab, -155);
    lv_obj_set_y(ui_cakeCPlab, 150);
    lv_obj_set_align(ui_cakeCPlab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_cakeCPlab, "COCOA POWDER     :");
    lv_obj_set_style_text_font(ui_cakeCPlab, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cakeCPtext = lv_textarea_create(ui_cake_panel);
    lv_obj_set_width(ui_cakeCPtext, 212);
    lv_obj_set_height(ui_cakeCPtext, 42);
    lv_obj_set_x(ui_cakeCPtext, 83);
    lv_obj_set_y(ui_cakeCPtext, 150);
    lv_obj_set_align(ui_cakeCPtext, LV_ALIGN_CENTER);
    if("0,1,2,3,4,5,6,7,8,9,." == "") lv_textarea_set_accepted_chars(ui_cakeCPtext, NULL);
    else lv_textarea_set_accepted_chars(ui_cakeCPtext, "0,1,2,3,4,5,6,7,8,9,.");
    lv_textarea_set_max_length(ui_cakeCPtext, 5);
    lv_textarea_set_text(ui_cakeCPtext, "187.5");
    lv_textarea_set_placeholder_text(ui_cakeCPtext, "Enter value in grams..");
    lv_obj_set_style_text_color(ui_cakeCPtext, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_cakeCPtext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_cakeCPtext, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_cakeCPtext, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_cakeCPtext, lv_color_hex(0xF6F583), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cakeCPtext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_cakeCPtext, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_cakeCPtext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_cakeCPtext, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_cakeCPtext, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_cakeCPtext, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_cakeCPtext, 255, LV_PART_MAIN | LV_STATE_FOCUSED);


    lv_obj_set_style_text_color(ui_cakeCPtext, lv_color_hex(0x000000), LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_cakeCPtext, 255, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_cakeCPtext, lv_color_hex(0x000000), LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_cakeCPtext, 255, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_FOCUSED);

    ui_g_flour_cake = lv_label_create(ui_cake_panel);
    lv_obj_set_width(ui_g_flour_cake, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_g_flour_cake, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_g_flour_cake, 212);
    lv_obj_set_y(ui_g_flour_cake, -150);
    lv_obj_set_align(ui_g_flour_cake, LV_ALIGN_CENTER);
    lv_label_set_text(ui_g_flour_cake, "g");

    ui_g_sug_cake = lv_label_create(ui_cake_panel);
    lv_obj_set_width(ui_g_sug_cake, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_g_sug_cake, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_g_sug_cake, 212);
    lv_obj_set_y(ui_g_sug_cake, -50);
    lv_obj_set_align(ui_g_sug_cake, LV_ALIGN_CENTER);
    lv_label_set_text(ui_g_sug_cake, "g");

    ui_g_bp_cake = lv_label_create(ui_cake_panel);
    lv_obj_set_width(ui_g_bp_cake, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_g_bp_cake, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_g_bp_cake, 212);
    lv_obj_set_y(ui_g_bp_cake, 50);
    lv_obj_set_align(ui_g_bp_cake, LV_ALIGN_CENTER);
    lv_label_set_text(ui_g_bp_cake, "g");

    ui_g_cp_cake = lv_label_create(ui_cake_panel);
    lv_obj_set_width(ui_g_cp_cake, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_g_cp_cake, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_g_cp_cake, 212);
    lv_obj_set_y(ui_g_cp_cake, 150);
    lv_obj_set_align(ui_g_cp_cake, LV_ALIGN_CENTER);
    lv_label_set_text(ui_g_cp_cake, "g");

    ui_Label10 = lv_label_create(ui_cake_panel);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, 87);
    lv_obj_set_y(ui_Label10, 186);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "*For Vanilla cake make equal to 0g.");
    lv_obj_set_style_text_color(ui_Label10, lv_color_hex(0xE0BD57), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel6 = lv_obj_create(ui_cake_panel);
    lv_obj_set_width(ui_Panel6, 134);
    lv_obj_set_height(ui_Panel6, 67);
    lv_obj_set_x(ui_Panel6, -309);
    lv_obj_set_y(ui_Panel6, -202);
    lv_obj_set_align(ui_Panel6, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel6, lv_color_hex(0x8C8C8C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel6, lv_color_hex(0xFFFC00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel6, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Panel6, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_angle(ui_Panel6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cake_main_label = lv_label_create(ui_cake_panel);
    lv_obj_set_width(ui_cake_main_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_cake_main_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_cake_main_label, -306);
    lv_obj_set_y(ui_cake_main_label, -199);
    lv_obj_set_align(ui_cake_main_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_cake_main_label, "CAKE");
    lv_obj_set_style_text_color(ui_cake_main_label, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_cake_main_label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_cake_main_label, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_angle(ui_cake_main_label, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cakeconfirm = lv_imgbtn_create(ui_cakerep);
    lv_imgbtn_set_src(ui_cakeconfirm, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_confirm_icon_png, NULL);
    lv_imgbtn_set_src(ui_cakeconfirm, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_confirm_icon_png, NULL);
    lv_imgbtn_set_src(ui_cakeconfirm, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_cakeconfirm, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_cakeconfirm, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_cakeconfirm, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_height(ui_cakeconfirm, 64);
    lv_obj_set_width(ui_cakeconfirm, LV_SIZE_CONTENT);   /// -137
    lv_obj_set_x(ui_cakeconfirm, -347);
    lv_obj_set_y(ui_cakeconfirm, 150);
    lv_obj_set_align(ui_cakeconfirm, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_cakeconfirm, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_cakeconfirm, lv_color_hex(0x36FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cakeconfirm, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_cakeconfirm, lv_color_hex(0x0F00FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_cakeconfirm, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cakekeyboard = lv_keyboard_create(ui_cakerep);
    lv_keyboard_set_mode(ui_cakekeyboard, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_width(ui_cakekeyboard, 673);
    lv_obj_set_height(ui_cakekeyboard, 228);
    lv_obj_set_x(ui_cakekeyboard, 55);
    lv_obj_set_y(ui_cakekeyboard, 97);
    lv_obj_set_align(ui_cakekeyboard, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_cakekeyboard, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_radius(ui_cakekeyboard, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_cakekeyboard, lv_color_hex(0x5C5C5C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cakekeyboard, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_cakekeyboard, 100, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_cakekeyboard, lv_color_hex(0xF9F59C), LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cakekeyboard, 255, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_cakekeyboard, lv_color_hex(0x000000), LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_cakekeyboard, 255, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_cakekeyboard, 1, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_cakekeyboard, LV_BORDER_SIDE_FULL, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_cakekeyboard, &lv_font_montserrat_20, LV_PART_ITEMS | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_cake_recipe, ui_event_cake_recipe, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_cake_home, ui_event_cake_home, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_cakeflourtext, ui_event_cakeflourtext, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_cakesugtext, ui_event_cakesugtext, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_cakeBPtext, ui_event_cakeBPtext, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_cakeCPtext, ui_event_cakeCPtext, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_cakeconfirm, ui_event_cakeconfirm, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_cakekeyboard, ui_cakeflourtext);
    lv_obj_add_event_cb(ui_cakerep, ui_event_cakerep, LV_EVENT_ALL, NULL);

}
