// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void getreadycake(lv_event_t * e)
{
	// Your code here
}

void getreadymuff(lv_event_t * e)
{
	// Your code here
}

void getreadycook(lv_event_t * e)
{
	// Your code here
}

void getreadybrown(lv_event_t * e)
{
	// Your code here
}

void getreadypan(lv_event_t * e)
{
	// Your code here
}

void getreadybread(lv_event_t * e)
{
	// Your code here
}

void getreadycup(lv_event_t * e)
{
	// Your code here
}

void getreadycus1(lv_event_t * e)
{
	// Your code here
}

void getreadycus2(lv_event_t * e)
{
	// Your code here
}

void getreadycus3(lv_event_t * e)
{
	// Your code here
}

void cakedone(lv_event_t * e)
{
	// Your code here
}

void muffdone(lv_event_t * e)
{
	// Your code here
}

void cookdone(lv_event_t * e)
{
	// Your code here
}

void browndone(lv_event_t * e)
{
	// Your code here
}

void pancakedone(lv_event_t * e)
{
	// Your code here
}

void breaddone(lv_event_t * e)
{
	// Your code here
}

void cupcakedone(lv_event_t * e)
{
	// Your code here
}

void cus1done(lv_event_t * e)
{
	// Your code here
}

void cus2done(lv_event_t * e)
{
	// Your code here
}

void cus3done(lv_event_t * e)
{
	// Your code here
}
