// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void getreadycake(lv_event_t * e);
void getreadymuff(lv_event_t * e);
void getreadycook(lv_event_t * e);
void getreadybrown(lv_event_t * e);
void getreadypan(lv_event_t * e);
void getreadybread(lv_event_t * e);
void getreadycup(lv_event_t * e);
void getreadycus1(lv_event_t * e);
void getreadycus2(lv_event_t * e);
void getreadycus3(lv_event_t * e);
void cakedone(lv_event_t * e);
void muffdone(lv_event_t * e);
void cookdone(lv_event_t * e);
void browndone(lv_event_t * e);
void pancakedone(lv_event_t * e);
void breaddone(lv_event_t * e);
void cupcakedone(lv_event_t * e);
void cus1done(lv_event_t * e);
void cus2done(lv_event_t * e);
void cus3done(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
