// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_muffrep_screen_init(void)
{
    ui_muffrep = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_muffrep, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_muffrep, lv_color_hex(0x454444), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_muffrep, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_muffrep, lv_color_hex(0x6E6E6E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_muffrep, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_muffrep, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_muffrep, LV_BORDER_SIDE_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_muff_recipe = lv_imgbtn_create(ui_muffrep);
    lv_imgbtn_set_src(ui_muff_recipe, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_kitchen_whisk_icon_png, NULL);
    lv_imgbtn_set_src(ui_muff_recipe, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_kitchen_whisk_icon_png, NULL);
    lv_imgbtn_set_src(ui_muff_recipe, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_muff_recipe, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_muff_recipe, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_muff_recipe, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_height(ui_muff_recipe, 72);
    lv_obj_set_width(ui_muff_recipe, LV_SIZE_CONTENT);   /// -137
    lv_obj_set_x(ui_muff_recipe, -340);
    lv_obj_set_y(ui_muff_recipe, -80);
    lv_obj_set_align(ui_muff_recipe, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_muff_recipe, lv_color_hex(0x6E6E6E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_muff_recipe, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_muff_recipe, lv_color_hex(0x0F00FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_muff_recipe, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_muff_home = lv_imgbtn_create(ui_muffrep);
    lv_imgbtn_set_src(ui_muff_home, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_home_icon_png, NULL);
    lv_imgbtn_set_src(ui_muff_home, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_home_icon_png, NULL);
    lv_imgbtn_set_src(ui_muff_home, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_muff_home, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_muff_home, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_muff_home, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_height(ui_muff_home, 79);
    lv_obj_set_width(ui_muff_home, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_muff_home, -347);
    lv_obj_set_y(ui_muff_home, -191);
    lv_obj_set_align(ui_muff_home, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_muff_home, lv_color_hex(0x6E6E6E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_muff_home, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_muff_page = lv_imgbtn_create(ui_muffrep);
    lv_imgbtn_set_src(ui_muff_page, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_muffin_icon_png, NULL);
    lv_imgbtn_set_src(ui_muff_page, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_muffin_icon_png, NULL);
    lv_imgbtn_set_src(ui_muff_page, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_muff_page, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_muff_page, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_muff_page, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_muff_page, 74);
    lv_obj_set_height(ui_muff_page, 74);
    lv_obj_set_x(ui_muff_page, -317);
    lv_obj_set_y(ui_muff_page, 25);
    lv_obj_set_align(ui_muff_page, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_muff_page, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_muff_page, lv_color_hex(0x32FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_muff_page, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_muff_page, lv_color_hex(0x32FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_muff_page, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_muff_page, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_muff_page, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_muff_page, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_muff_page, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_muff_page, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_muff_page, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_muff_panel = lv_obj_create(ui_muffrep);
    lv_obj_set_width(ui_muff_panel, 696);
    lv_obj_set_height(ui_muff_panel, 482);
    lv_obj_set_x(ui_muff_panel, 60);
    lv_obj_set_y(ui_muff_panel, 10);
    lv_obj_set_align(ui_muff_panel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_muff_panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_muff_panel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_muff_panel, lv_color_hex(0xECE7D6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_muff_panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_muff_panel, lv_color_hex(0x32FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_muff_panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_muff_panel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_muff_panel, LV_BORDER_SIDE_TOP, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_shadow_color(ui_muff_panel, lv_color_hex(0x32FF00), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_muff_panel, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_muff_panel, 20, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_muff_panel, 1, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_muff_panel, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_muff_panel, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_muffflourlab1 = lv_label_create(ui_muff_panel);
    lv_obj_set_width(ui_muffflourlab1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_muffflourlab1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_muffflourlab1, -128);
    lv_obj_set_y(ui_muffflourlab1, -150);
    lv_obj_set_align(ui_muffflourlab1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_muffflourlab1, "FLOUR                 :");
    lv_obj_set_style_text_font(ui_muffflourlab1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_muffflourtext1 = lv_textarea_create(ui_muff_panel);
    lv_obj_set_width(ui_muffflourtext1, 212);
    lv_obj_set_height(ui_muffflourtext1, 42);
    lv_obj_set_x(ui_muffflourtext1, 82);
    lv_obj_set_y(ui_muffflourtext1, -150);
    lv_obj_set_align(ui_muffflourtext1, LV_ALIGN_CENTER);
    if("0,1,2,3,4,5,6,7,8,9,." == "") lv_textarea_set_accepted_chars(ui_muffflourtext1, NULL);
    else lv_textarea_set_accepted_chars(ui_muffflourtext1, "0,1,2,3,4,5,6,7,8,9,.");
    lv_textarea_set_max_length(ui_muffflourtext1, 5);
    lv_textarea_set_text(ui_muffflourtext1, "375");
    lv_textarea_set_placeholder_text(ui_muffflourtext1, "Enter value in grams...");
    lv_obj_set_style_text_color(ui_muffflourtext1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_muffflourtext1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_muffflourtext1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_muffflourtext1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_muffflourtext1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_muffflourtext1, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_muffflourtext1, lv_color_hex(0x85F16A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_muffflourtext1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_muffflourtext1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_muffflourtext1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_muffflourtext1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_muffflourtext1, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_muffflourtext1, lv_color_hex(0x8C8C8C), LV_PART_MAIN | LV_STATE_EDITED);
    lv_obj_set_style_bg_opa(ui_muffflourtext1, 255, LV_PART_MAIN | LV_STATE_EDITED);
    lv_obj_set_style_text_color(ui_muffflourtext1, lv_color_hex(0x050505), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_muffflourtext1, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_color(ui_muffflourtext1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_muffflourtext1, 255, LV_PART_MAIN | LV_STATE_FOCUSED);


    lv_obj_set_style_text_color(ui_muffflourtext1, lv_color_hex(0x000000), LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_muffflourtext1, 255, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_muffflourtext1, lv_color_hex(0x050505), LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_muffflourtext1, 255, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_FOCUSED);

    ui_muffsuglab1 = lv_label_create(ui_muff_panel);
    lv_obj_set_width(ui_muffsuglab1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_muffsuglab1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_muffsuglab1, -128);
    lv_obj_set_y(ui_muffsuglab1, -50);
    lv_obj_set_align(ui_muffsuglab1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_muffsuglab1, "SUGAR                 :");
    lv_obj_set_style_text_font(ui_muffsuglab1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_muffBPlab1 = lv_label_create(ui_muff_panel);
    lv_obj_set_width(ui_muffBPlab1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_muffBPlab1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_muffBPlab1, -155);
    lv_obj_set_y(ui_muffBPlab1, 50);
    lv_obj_set_align(ui_muffBPlab1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_muffBPlab1, "BAKING POWDER     :");
    lv_obj_set_style_text_font(ui_muffBPlab1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_muffsugtext1 = lv_textarea_create(ui_muff_panel);
    lv_obj_set_width(ui_muffsugtext1, 212);
    lv_obj_set_height(ui_muffsugtext1, 42);
    lv_obj_set_x(ui_muffsugtext1, 82);
    lv_obj_set_y(ui_muffsugtext1, -50);
    lv_obj_set_align(ui_muffsugtext1, LV_ALIGN_CENTER);
    if("0,1,2,3,4,5,6,7,8,9,." == "") lv_textarea_set_accepted_chars(ui_muffsugtext1, NULL);
    else lv_textarea_set_accepted_chars(ui_muffsugtext1, "0,1,2,3,4,5,6,7,8,9,.");
    lv_textarea_set_max_length(ui_muffsugtext1, 5);
    lv_textarea_set_text(ui_muffsugtext1, "125");
    lv_textarea_set_placeholder_text(ui_muffsugtext1, "Enter value in grams...");
    lv_obj_set_style_text_color(ui_muffsugtext1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_muffsugtext1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_muffsugtext1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_muffsugtext1, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_muffsugtext1, lv_color_hex(0x85F16A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_muffsugtext1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_muffsugtext1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_muffsugtext1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_muffsugtext1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_muffsugtext1, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_muffsugtext1, lv_color_hex(0x030303), LV_PART_MAIN | LV_STATE_EDITED);
    lv_obj_set_style_text_opa(ui_muffsugtext1, 255, LV_PART_MAIN | LV_STATE_EDITED);
    lv_obj_set_style_bg_color(ui_muffsugtext1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_muffsugtext1, 255, LV_PART_MAIN | LV_STATE_FOCUSED);


    lv_obj_set_style_text_color(ui_muffsugtext1, lv_color_hex(0x000000), LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_muffsugtext1, 255, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_muffsugtext1, lv_color_hex(0x040404), LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_muffsugtext1, 255, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_FOCUSED);

    ui_muffBPtext1 = lv_textarea_create(ui_muff_panel);
    lv_obj_set_width(ui_muffBPtext1, 212);
    lv_obj_set_height(ui_muffBPtext1, 42);
    lv_obj_set_x(ui_muffBPtext1, 83);
    lv_obj_set_y(ui_muffBPtext1, 50);
    lv_obj_set_align(ui_muffBPtext1, LV_ALIGN_CENTER);
    if("0,1,2,3,4,5,6,7,8,9,." == "") lv_textarea_set_accepted_chars(ui_muffBPtext1, NULL);
    else lv_textarea_set_accepted_chars(ui_muffBPtext1, "0,1,2,3,4,5,6,7,8,9,.");
    lv_textarea_set_max_length(ui_muffBPtext1, 5);
    lv_textarea_set_text(ui_muffBPtext1, "7.5");
    lv_textarea_set_placeholder_text(ui_muffBPtext1, "Enter value in grams...");
    lv_obj_set_style_text_color(ui_muffBPtext1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_muffBPtext1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_muffBPtext1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_muffBPtext1, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_muffBPtext1, lv_color_hex(0x85F16A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_muffBPtext1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_muffBPtext1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_muffBPtext1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_muffBPtext1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_muffBPtext1, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_muffBPtext1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_muffBPtext1, 255, LV_PART_MAIN | LV_STATE_FOCUSED);


    lv_obj_set_style_text_color(ui_muffBPtext1, lv_color_hex(0x000000), LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_muffBPtext1, 255, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_muffBPtext1, lv_color_hex(0x010101), LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_muffBPtext1, 255, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_FOCUSED);

    ui_muffCPlab1 = lv_label_create(ui_muff_panel);
    lv_obj_set_width(ui_muffCPlab1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_muffCPlab1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_muffCPlab1, -155);
    lv_obj_set_y(ui_muffCPlab1, 150);
    lv_obj_set_align(ui_muffCPlab1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_muffCPlab1, "COCOA POWDER     :");
    lv_obj_set_style_text_font(ui_muffCPlab1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_muffCPtext1 = lv_textarea_create(ui_muff_panel);
    lv_obj_set_width(ui_muffCPtext1, 212);
    lv_obj_set_height(ui_muffCPtext1, 42);
    lv_obj_set_x(ui_muffCPtext1, 83);
    lv_obj_set_y(ui_muffCPtext1, 150);
    lv_obj_set_align(ui_muffCPtext1, LV_ALIGN_CENTER);
    if("0,1,2,3,4,5,6,7,8,9,." == "") lv_textarea_set_accepted_chars(ui_muffCPtext1, NULL);
    else lv_textarea_set_accepted_chars(ui_muffCPtext1, "0,1,2,3,4,5,6,7,8,9,.");
    lv_textarea_set_max_length(ui_muffCPtext1, 5);
    lv_textarea_set_text(ui_muffCPtext1, "125");
    lv_textarea_set_placeholder_text(ui_muffCPtext1, "Enter value in grams...");
    lv_obj_set_style_text_color(ui_muffCPtext1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_muffCPtext1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_muffCPtext1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_muffCPtext1, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_muffCPtext1, lv_color_hex(0x85F16A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_muffCPtext1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_muffCPtext1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_muffCPtext1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_muffCPtext1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_muffCPtext1, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_muffCPtext1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_muffCPtext1, 255, LV_PART_MAIN | LV_STATE_FOCUSED);


    lv_obj_set_style_text_color(ui_muffCPtext1, lv_color_hex(0x000000), LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_muffCPtext1, 255, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_muffCPtext1, lv_color_hex(0x000000), LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_muffCPtext1, 255, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_FOCUSED);

    ui_g_flour1 = lv_label_create(ui_muff_panel);
    lv_obj_set_width(ui_g_flour1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_g_flour1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_g_flour1, 212);
    lv_obj_set_y(ui_g_flour1, -150);
    lv_obj_set_align(ui_g_flour1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_g_flour1, "g");

    ui_g_sug1 = lv_label_create(ui_muff_panel);
    lv_obj_set_width(ui_g_sug1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_g_sug1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_g_sug1, 212);
    lv_obj_set_y(ui_g_sug1, -50);
    lv_obj_set_align(ui_g_sug1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_g_sug1, "g");

    ui_g_bp1 = lv_label_create(ui_muff_panel);
    lv_obj_set_width(ui_g_bp1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_g_bp1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_g_bp1, 212);
    lv_obj_set_y(ui_g_bp1, 50);
    lv_obj_set_align(ui_g_bp1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_g_bp1, "g");

    ui_g_cp1 = lv_label_create(ui_muff_panel);
    lv_obj_set_width(ui_g_cp1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_g_cp1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_g_cp1, 212);
    lv_obj_set_y(ui_g_cp1, 150);
    lv_obj_set_align(ui_g_cp1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_g_cp1, "g");

    ui_Label11 = lv_label_create(ui_muff_panel);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, 87);
    lv_obj_set_y(ui_Label11, 186);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "*For Vanilla muffin make equal to 0g.");
    lv_obj_set_style_text_color(ui_Label11, lv_color_hex(0xE0BD57), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label12 = lv_label_create(ui_muff_panel);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, 87);
    lv_obj_set_y(ui_Label12, 85);
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "*For Self Raising Flour make equal to 0g.");
    lv_obj_set_style_text_color(ui_Label12, lv_color_hex(0xE0BD57), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel7 = lv_obj_create(ui_muff_panel);
    lv_obj_set_width(ui_Panel7, 134);
    lv_obj_set_height(ui_Panel7, 67);
    lv_obj_set_x(ui_Panel7, -309);
    lv_obj_set_y(ui_Panel7, -202);
    lv_obj_set_align(ui_Panel7, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel7, lv_color_hex(0x8C8C8C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel7, lv_color_hex(0x32FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel7, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Panel7, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_angle(ui_Panel7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label14 = lv_label_create(ui_muff_panel);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label14, -295);
    lv_obj_set_y(ui_Label14, -201);
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "MUFFINS");
    lv_obj_set_style_text_color(ui_Label14, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label14, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_angle(ui_Label14, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_muffconfirm = lv_imgbtn_create(ui_muffrep);
    lv_imgbtn_set_src(ui_muffconfirm, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_confirm_icon_png, NULL);
    lv_imgbtn_set_src(ui_muffconfirm, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_confirm_icon_png, NULL);
    lv_imgbtn_set_src(ui_muffconfirm, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_muffconfirm, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_muffconfirm, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_muffconfirm, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_height(ui_muffconfirm, 64);
    lv_obj_set_width(ui_muffconfirm, LV_SIZE_CONTENT);   /// -137
    lv_obj_set_x(ui_muffconfirm, -347);
    lv_obj_set_y(ui_muffconfirm, 150);
    lv_obj_set_align(ui_muffconfirm, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_muffconfirm, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_muffconfirm, lv_color_hex(0x36FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_muffconfirm, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_muffconfirm, lv_color_hex(0x0F00FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_muffconfirm, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_muffkeyboard = lv_keyboard_create(ui_muffrep);
    lv_keyboard_set_mode(ui_muffkeyboard, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_width(ui_muffkeyboard, 673);
    lv_obj_set_height(ui_muffkeyboard, 228);
    lv_obj_set_x(ui_muffkeyboard, 55);
    lv_obj_set_y(ui_muffkeyboard, 97);
    lv_obj_set_align(ui_muffkeyboard, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_muffkeyboard, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_radius(ui_muffkeyboard, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_muffkeyboard, lv_color_hex(0x5C5C5C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_muffkeyboard, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_muffkeyboard, 100, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_muffkeyboard, lv_color_hex(0x8CEF91), LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_muffkeyboard, 255, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_muffkeyboard, lv_color_hex(0x000000), LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_muffkeyboard, 255, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_muffkeyboard, 1, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_muffkeyboard, LV_BORDER_SIDE_FULL, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_muffkeyboard, &lv_font_montserrat_20, LV_PART_ITEMS | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_muff_recipe, ui_event_muff_recipe, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_muff_home, ui_event_muff_home, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_muffflourtext1, ui_event_muffflourtext1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_muffsugtext1, ui_event_muffsugtext1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_muffBPtext1, ui_event_muffBPtext1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_muffCPtext1, ui_event_muffCPtext1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_muffconfirm, ui_event_muffconfirm, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_muffkeyboard, ui_cakeflourtext);
    lv_obj_add_event_cb(ui_muffrep, ui_event_muffrep, LV_EVENT_ALL, NULL);

}
