// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Home
void ui_Home_screen_init(void);
extern lv_obj_t * ui_Home;
extern lv_obj_t * ui_home_home;
extern lv_obj_t * ui_home_panel;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_Label22;
void ui_event_recipe_button1(lv_event_t * e);
extern lv_obj_t * ui_recipe_button1;
extern lv_obj_t * ui_Bar1;
extern lv_obj_t * ui_Bar2;
extern lv_obj_t * ui_Bar3;
extern lv_obj_t * ui_Bar4;
// SCREEN: ui_recipe
void ui_recipe_screen_init(void);
extern lv_obj_t * ui_recipe;
extern lv_obj_t * ui_recipe_button2;
void ui_event_recipe_home(lv_event_t * e);
extern lv_obj_t * ui_recipe_home;
extern lv_obj_t * ui_recipepanel;
void ui_event_cake(lv_event_t * e);
extern lv_obj_t * ui_cake;
extern lv_obj_t * ui_Label2;
void ui_event_muf(lv_event_t * e);
extern lv_obj_t * ui_muf;
extern lv_obj_t * ui_Label1;
void ui_event_cook(lv_event_t * e);
extern lv_obj_t * ui_cook;
extern lv_obj_t * ui_Label3;
void ui_event_brownies(lv_event_t * e);
extern lv_obj_t * ui_brownies;
extern lv_obj_t * ui_Label4;
void ui_event_pancake(lv_event_t * e);
extern lv_obj_t * ui_pancake;
extern lv_obj_t * ui_Label5;
void ui_event_bread(lv_event_t * e);
extern lv_obj_t * ui_bread;
extern lv_obj_t * ui_Label6;
void ui_event_cup(lv_event_t * e);
extern lv_obj_t * ui_cup;
extern lv_obj_t * ui_Label7;
void ui_event_add1(lv_event_t * e);
extern lv_obj_t * ui_add1;
extern lv_obj_t * ui_Label8;
void ui_event_add2(lv_event_t * e);
extern lv_obj_t * ui_add2;
extern lv_obj_t * ui_Label9;
void ui_event_Button9(lv_event_t * e);
extern lv_obj_t * ui_Button9;
extern lv_obj_t * ui_add3;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_Image6;
extern lv_obj_t * ui_Image7;
extern lv_obj_t * ui_Image8;
extern lv_obj_t * ui_Image9;
extern lv_obj_t * ui_Image10;
// SCREEN: ui_cakerep
void ui_cakerep_screen_init(void);
void ui_event_cakerep(lv_event_t * e);
extern lv_obj_t * ui_cakerep;
void ui_event_cake_recipe(lv_event_t * e);
extern lv_obj_t * ui_cake_recipe;
void ui_event_cake_home(lv_event_t * e);
extern lv_obj_t * ui_cake_home;
extern lv_obj_t * ui_ImgButton7;
extern lv_obj_t * ui_cake_panel;
extern lv_obj_t * ui_cakeflourlab;
void ui_event_cakeflourtext(lv_event_t * e);
extern lv_obj_t * ui_cakeflourtext;
extern lv_obj_t * ui_cakesuglab;
extern lv_obj_t * ui_cakeBPlab;
void ui_event_cakesugtext(lv_event_t * e);
extern lv_obj_t * ui_cakesugtext;
void ui_event_cakeBPtext(lv_event_t * e);
extern lv_obj_t * ui_cakeBPtext;
extern lv_obj_t * ui_cakeCPlab;
void ui_event_cakeCPtext(lv_event_t * e);
extern lv_obj_t * ui_cakeCPtext;
extern lv_obj_t * ui_g_flour_cake;
extern lv_obj_t * ui_g_sug_cake;
extern lv_obj_t * ui_g_bp_cake;
extern lv_obj_t * ui_g_cp_cake;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Panel6;
extern lv_obj_t * ui_cake_main_label;
void ui_event_cakeconfirm(lv_event_t * e);
extern lv_obj_t * ui_cakeconfirm;
extern lv_obj_t * ui_cakekeyboard;
// SCREEN: ui_muffrep
void ui_muffrep_screen_init(void);
void ui_event_muffrep(lv_event_t * e);
extern lv_obj_t * ui_muffrep;
void ui_event_muff_recipe(lv_event_t * e);
extern lv_obj_t * ui_muff_recipe;
void ui_event_muff_home(lv_event_t * e);
extern lv_obj_t * ui_muff_home;
extern lv_obj_t * ui_muff_page;
extern lv_obj_t * ui_muff_panel;
extern lv_obj_t * ui_muffflourlab1;
void ui_event_muffflourtext1(lv_event_t * e);
extern lv_obj_t * ui_muffflourtext1;
extern lv_obj_t * ui_muffsuglab1;
extern lv_obj_t * ui_muffBPlab1;
void ui_event_muffsugtext1(lv_event_t * e);
extern lv_obj_t * ui_muffsugtext1;
void ui_event_muffBPtext1(lv_event_t * e);
extern lv_obj_t * ui_muffBPtext1;
extern lv_obj_t * ui_muffCPlab1;
void ui_event_muffCPtext1(lv_event_t * e);
extern lv_obj_t * ui_muffCPtext1;
extern lv_obj_t * ui_g_flour1;
extern lv_obj_t * ui_g_sug1;
extern lv_obj_t * ui_g_bp1;
extern lv_obj_t * ui_g_cp1;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Panel7;
extern lv_obj_t * ui_Label14;
void ui_event_muffconfirm(lv_event_t * e);
extern lv_obj_t * ui_muffconfirm;
extern lv_obj_t * ui_muffkeyboard;
// SCREEN: ui_cookrep
void ui_cookrep_screen_init(void);
void ui_event_cookrep(lv_event_t * e);
extern lv_obj_t * ui_cookrep;
void ui_event_cook_rep(lv_event_t * e);
extern lv_obj_t * ui_cook_rep;
void ui_event_cook_home(lv_event_t * e);
extern lv_obj_t * ui_cook_home;
extern lv_obj_t * ui_cook_page;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_cookflourlab;
void ui_event_cookflourtext(lv_event_t * e);
extern lv_obj_t * ui_cookflourtext;
extern lv_obj_t * ui_cooksuglab;
extern lv_obj_t * ui_cookBPlab;
void ui_event_cooksugtext(lv_event_t * e);
extern lv_obj_t * ui_cooksugtext;
void ui_event_cookBPtext(lv_event_t * e);
extern lv_obj_t * ui_cookBPtext;
extern lv_obj_t * ui_cookCPlab;
void ui_event_cookCPtext(lv_event_t * e);
extern lv_obj_t * ui_cookCPtext;
extern lv_obj_t * ui_g_flour2;
extern lv_obj_t * ui_g_sug2;
extern lv_obj_t * ui_g_bp2;
extern lv_obj_t * ui_g_cp2;
extern lv_obj_t * ui_Panel8;
extern lv_obj_t * ui_Label15;
void ui_event_cookconfirm(lv_event_t * e);
extern lv_obj_t * ui_cookconfirm;
extern lv_obj_t * ui_cookkeyboard1;
// SCREEN: ui_brownrep
void ui_brownrep_screen_init(void);
void ui_event_brownrep(lv_event_t * e);
extern lv_obj_t * ui_brownrep;
void ui_event_brown_rep(lv_event_t * e);
extern lv_obj_t * ui_brown_rep;
void ui_event_brown_home(lv_event_t * e);
extern lv_obj_t * ui_brown_home;
extern lv_obj_t * ui_brown_page;
extern lv_obj_t * ui_Panel9;
extern lv_obj_t * ui_brownflourlab;
void ui_event_brownflourtext1(lv_event_t * e);
extern lv_obj_t * ui_brownflourtext1;
extern lv_obj_t * ui_brownsuglab1;
extern lv_obj_t * ui_brownBPlab1;
void ui_event_brownsugtext1(lv_event_t * e);
extern lv_obj_t * ui_brownsugtext1;
void ui_event_brownBPtext1(lv_event_t * e);
extern lv_obj_t * ui_brownBPtext1;
extern lv_obj_t * ui_brownCPlab1;
void ui_event_brownCPtext1(lv_event_t * e);
extern lv_obj_t * ui_brownCPtext1;
extern lv_obj_t * ui_g_flour3;
extern lv_obj_t * ui_g_sug3;
extern lv_obj_t * ui_g_bp3;
extern lv_obj_t * ui_g_cp3;
extern lv_obj_t * ui_Panel10;
extern lv_obj_t * ui_Label16;
void ui_event_brownconfirm(lv_event_t * e);
extern lv_obj_t * ui_brownconfirm;
extern lv_obj_t * ui_brownkeyboard;
// SCREEN: ui_pancakesrep
void ui_pancakesrep_screen_init(void);
void ui_event_pancakesrep(lv_event_t * e);
extern lv_obj_t * ui_pancakesrep;
void ui_event_pancake_rep(lv_event_t * e);
extern lv_obj_t * ui_pancake_rep;
void ui_event_pancake_home(lv_event_t * e);
extern lv_obj_t * ui_pancake_home;
extern lv_obj_t * ui_pancake_page;
extern lv_obj_t * ui_Panel11;
extern lv_obj_t * ui_pancakesflourlab;
void ui_event_pancakesflourtext(lv_event_t * e);
extern lv_obj_t * ui_pancakesflourtext;
extern lv_obj_t * ui_pancakessuglab2;
extern lv_obj_t * ui_pancakesBPlab2;
void ui_event_pancakessugtext(lv_event_t * e);
extern lv_obj_t * ui_pancakessugtext;
void ui_event_pancakesBPtext(lv_event_t * e);
extern lv_obj_t * ui_pancakesBPtext;
extern lv_obj_t * ui_g_flour4;
extern lv_obj_t * ui_g_sug4;
extern lv_obj_t * ui_g_bp4;
extern lv_obj_t * ui_Panel12;
extern lv_obj_t * ui_Label17;
void ui_event_pancakesconfirm(lv_event_t * e);
extern lv_obj_t * ui_pancakesconfirm;
extern lv_obj_t * ui_pancakeskeyboard;
// SCREEN: ui_breadrep
void ui_breadrep_screen_init(void);
void ui_event_breadrep(lv_event_t * e);
extern lv_obj_t * ui_breadrep;
void ui_event_bread_rep(lv_event_t * e);
extern lv_obj_t * ui_bread_rep;
void ui_event_bread_home(lv_event_t * e);
extern lv_obj_t * ui_bread_home;
extern lv_obj_t * ui_bread_page;
extern lv_obj_t * ui_Panel13;
extern lv_obj_t * ui_breadflourlab;
void ui_event_breadflourtext(lv_event_t * e);
extern lv_obj_t * ui_breadflourtext;
extern lv_obj_t * ui_breadsuglab;
extern lv_obj_t * ui_breadBPlab;
void ui_event_breadsugtext(lv_event_t * e);
extern lv_obj_t * ui_breadsugtext;
void ui_event_breadBPtext(lv_event_t * e);
extern lv_obj_t * ui_breadBPtext;
extern lv_obj_t * ui_g_flour5;
extern lv_obj_t * ui_g_sug5;
extern lv_obj_t * ui_g_bp5;
extern lv_obj_t * ui_Panel14;
extern lv_obj_t * ui_Label18;
void ui_event_breadconfirm(lv_event_t * e);
extern lv_obj_t * ui_breadconfirm;
extern lv_obj_t * ui_breadkeyboard;
// SCREEN: ui_cupcakesrep
void ui_cupcakesrep_screen_init(void);
void ui_event_cupcakesrep(lv_event_t * e);
extern lv_obj_t * ui_cupcakesrep;
void ui_event_cup_recipe(lv_event_t * e);
extern lv_obj_t * ui_cup_recipe;
void ui_event_cup_home(lv_event_t * e);
extern lv_obj_t * ui_cup_home;
extern lv_obj_t * ui_cup_page;
extern lv_obj_t * ui_cupcakepanel;
extern lv_obj_t * ui_cupflourlab;
void ui_event_cupflourtext(lv_event_t * e);
extern lv_obj_t * ui_cupflourtext;
extern lv_obj_t * ui_cupsuglab;
extern lv_obj_t * ui_cupBPlab;
extern lv_obj_t * ui_cupCPlab;
extern lv_obj_t * ui_g_flour_cup;
extern lv_obj_t * ui_g_sug_cup;
extern lv_obj_t * ui_g_bp_cup;
extern lv_obj_t * ui_g_cp_cup;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Label13;
void ui_event_cupsugtext(lv_event_t * e);
extern lv_obj_t * ui_cupsugtext;
void ui_event_cupBPtext(lv_event_t * e);
extern lv_obj_t * ui_cupBPtext;
void ui_event_cupCPtext(lv_event_t * e);
extern lv_obj_t * ui_cupCPtext;
void ui_event_cupconfirm(lv_event_t * e);
extern lv_obj_t * ui_cupconfirm;
extern lv_obj_t * ui_cupkeyboard1;
// SCREEN: ui_custom1rep
void ui_custom1rep_screen_init(void);
void ui_event_custom1rep(lv_event_t * e);
extern lv_obj_t * ui_custom1rep;
void ui_event_cus1_recipe(lv_event_t * e);
extern lv_obj_t * ui_cus1_recipe;
void ui_event_cus1_home(lv_event_t * e);
extern lv_obj_t * ui_cus1_home;
extern lv_obj_t * ui_cus1_page;
extern lv_obj_t * ui_cus1panel;
extern lv_obj_t * ui_cus1flourlab;
void ui_event_cus1flourtext(lv_event_t * e);
extern lv_obj_t * ui_cus1flourtext;
extern lv_obj_t * ui_cus1suglab;
extern lv_obj_t * ui_cus1BPlab;
extern lv_obj_t * ui_cus1CPlab;
extern lv_obj_t * ui_g_flour_cus1;
extern lv_obj_t * ui_g_sug_cus1;
extern lv_obj_t * ui_g_bp_cus1;
extern lv_obj_t * ui_g_cp_cus1;
void ui_event_cus1nametext(lv_event_t * e);
extern lv_obj_t * ui_cus1nametext;
extern lv_obj_t * ui_cus1namelab;
void ui_event_cus1sugtext(lv_event_t * e);
extern lv_obj_t * ui_cus1sugtext;
void ui_event_cus1BPtext(lv_event_t * e);
extern lv_obj_t * ui_cus1BPtext;
void ui_event_cus1CPtext(lv_event_t * e);
extern lv_obj_t * ui_cus1CPtext;
void ui_event_cus1confirm(lv_event_t * e);
extern lv_obj_t * ui_cus1confirm;
extern lv_obj_t * ui_cus1keyboard_num;
extern lv_obj_t * ui_cus1keyboard_let;
// SCREEN: ui_custom2rep
void ui_custom2rep_screen_init(void);
void ui_event_custom2rep(lv_event_t * e);
extern lv_obj_t * ui_custom2rep;
void ui_event_cus2_recipe(lv_event_t * e);
extern lv_obj_t * ui_cus2_recipe;
void ui_event_cus2_home(lv_event_t * e);
extern lv_obj_t * ui_cus2_home;
extern lv_obj_t * ui_cus2_page;
extern lv_obj_t * ui_cus2panel;
extern lv_obj_t * ui_cus2flourlab;
extern lv_obj_t * ui_cus2suglab;
extern lv_obj_t * ui_cus2BPlab;
extern lv_obj_t * ui_cus2CPlab;
extern lv_obj_t * ui_g_flour_cus2;
extern lv_obj_t * ui_g_sug_cus2;
extern lv_obj_t * ui_g_bp_cus2;
extern lv_obj_t * ui_g_cp_cus2;
void ui_event_cus2nametext(lv_event_t * e);
extern lv_obj_t * ui_cus2nametext;
extern lv_obj_t * ui_cus2namelab;
void ui_event_cus2flourtext(lv_event_t * e);
extern lv_obj_t * ui_cus2flourtext;
void ui_event_cus2sugtext(lv_event_t * e);
extern lv_obj_t * ui_cus2sugtext;
void ui_event_cus2BPtext(lv_event_t * e);
extern lv_obj_t * ui_cus2BPtext;
void ui_event_cus2CPtext(lv_event_t * e);
extern lv_obj_t * ui_cus2CPtext;
void ui_event_cus2confirm1(lv_event_t * e);
extern lv_obj_t * ui_cus2confirm1;
extern lv_obj_t * ui_cus2keyboard_num;
extern lv_obj_t * ui_cus2keyboard_let;
// SCREEN: ui_custom3rep
void ui_custom3rep_screen_init(void);
void ui_event_custom3rep(lv_event_t * e);
extern lv_obj_t * ui_custom3rep;
void ui_event_cus3_recipe(lv_event_t * e);
extern lv_obj_t * ui_cus3_recipe;
void ui_event_cus3_home(lv_event_t * e);
extern lv_obj_t * ui_cus3_home;
extern lv_obj_t * ui_cus3_page;
extern lv_obj_t * ui_cus3panel;
extern lv_obj_t * ui_cus3flourlab;
extern lv_obj_t * ui_cus3suglab;
extern lv_obj_t * ui_cus3BPlab;
extern lv_obj_t * ui_cus3CPlab;
extern lv_obj_t * ui_g_flour_cus3;
extern lv_obj_t * ui_g_sug_cus3;
extern lv_obj_t * ui_g_bp_cus3;
extern lv_obj_t * ui_g_cp_cus3;
void ui_event_cus3nametext(lv_event_t * e);
extern lv_obj_t * ui_cus3nametext;
extern lv_obj_t * ui_cus3namelab;
void ui_event_cus3flourtext(lv_event_t * e);
extern lv_obj_t * ui_cus3flourtext;
void ui_event_cus3sugtext(lv_event_t * e);
extern lv_obj_t * ui_cus3sugtext;
void ui_event_cus3BPtext(lv_event_t * e);
extern lv_obj_t * ui_cus3BPtext;
void ui_event_cus3CPtext(lv_event_t * e);
extern lv_obj_t * ui_cus3CPtext;
void ui_event_cus3confirm(lv_event_t * e);
extern lv_obj_t * ui_cus3confirm;
extern lv_obj_t * ui_cus3keyboard_num;
extern lv_obj_t * ui_cus3keyboard_let;
extern lv_obj_t * ui____initial_actions0;
extern int Cake_Init;
extern int Muffin_Init;
extern int Cookies_Init;
extern int Brownies_Init;
extern int Pancakes_Init;
extern int Bread_Init;
extern int Cupcakes_Init;
extern int Cus1_recipe_Init;
extern int Cus2_recipe_Init;
extern int Cus3_recipe_Init;
extern int cake_confirm;
extern int muffin_confirm;
extern int cookie_confirm;
extern int brownie_confirm;
extern int pancake_confirm;
extern int bread_confirm;
extern int cupcake_confirm;
extern int cus1_confirm;
extern int cus2_confirm;
extern int cus3_confirm;


LV_IMG_DECLARE(ui__temporary_image);
LV_IMG_DECLARE(ui_img_home_icon_png);    // assets/home_icon.png
LV_IMG_DECLARE(ui_img_kitchen_whisk_icon_png);    // assets/kitchen_whisk_icon.png
LV_IMG_DECLARE(ui_img_book_label_png);    // assets/book_label.png
LV_IMG_DECLARE(ui_img_cake_icon_png);    // assets/cake_icon.png
LV_IMG_DECLARE(ui_img_confirm_icon_png);    // assets/confirm_icon.png
LV_IMG_DECLARE(ui_img_muffin_icon_png);    // assets/muffin_icon.png
LV_IMG_DECLARE(ui_img_cookie_half_icon_png);    // assets/cookie_half_icon.png
LV_IMG_DECLARE(ui_img_chocolate_bar_icon_png);    // assets/chocolate_bar_icon.png
LV_IMG_DECLARE(ui_img_pancake_icon_png);    // assets/pancake_icon.png
LV_IMG_DECLARE(ui_img_bread_icon_png);    // assets/bread_icon.png
LV_IMG_DECLARE(ui_img_cupcake_icon_png);    // assets/cupcake_icon.png
LV_IMG_DECLARE(ui_img_add_circle_png);    // assets/add_circle.png






void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
