// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_breadrep_screen_init(void)
{
    ui_breadrep = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_breadrep, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_breadrep, lv_color_hex(0x454444), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_breadrep, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_breadrep, lv_color_hex(0x6E6E6E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_breadrep, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_breadrep, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_breadrep, LV_BORDER_SIDE_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_bread_rep = lv_imgbtn_create(ui_breadrep);
    lv_imgbtn_set_src(ui_bread_rep, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_kitchen_whisk_icon_png, NULL);
    lv_imgbtn_set_src(ui_bread_rep, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_kitchen_whisk_icon_png, NULL);
    lv_imgbtn_set_src(ui_bread_rep, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_bread_rep, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_bread_rep, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_bread_rep, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_height(ui_bread_rep, 72);
    lv_obj_set_width(ui_bread_rep, LV_SIZE_CONTENT);   /// -137
    lv_obj_set_x(ui_bread_rep, -340);
    lv_obj_set_y(ui_bread_rep, -80);
    lv_obj_set_align(ui_bread_rep, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_bread_rep, lv_color_hex(0x6E6E6E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_bread_rep, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_bread_rep, lv_color_hex(0x0F00FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_bread_rep, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_bread_home = lv_imgbtn_create(ui_breadrep);
    lv_imgbtn_set_src(ui_bread_home, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_home_icon_png, NULL);
    lv_imgbtn_set_src(ui_bread_home, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_home_icon_png, NULL);
    lv_imgbtn_set_src(ui_bread_home, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_bread_home, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_bread_home, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_bread_home, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_height(ui_bread_home, 79);
    lv_obj_set_width(ui_bread_home, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_bread_home, -347);
    lv_obj_set_y(ui_bread_home, -191);
    lv_obj_set_align(ui_bread_home, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_bread_home, lv_color_hex(0x6E6E6E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_bread_home, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_bread_page = lv_imgbtn_create(ui_breadrep);
    lv_imgbtn_set_src(ui_bread_page, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_bread_icon_png, NULL);
    lv_imgbtn_set_src(ui_bread_page, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_bread_icon_png, NULL);
    lv_imgbtn_set_src(ui_bread_page, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_bread_page, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_bread_page, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_bread_page, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_bread_page, 86);
    lv_obj_set_height(ui_bread_page, 74);
    lv_obj_set_x(ui_bread_page, -318);
    lv_obj_set_y(ui_bread_page, 25);
    lv_obj_set_align(ui_bread_page, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_bread_page, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_bread_page, lv_color_hex(0x0F00FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_bread_page, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_bread_page, lv_color_hex(0x0F00FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_bread_page, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_bread_page, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_bread_page, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_bread_page, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_bread_page, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_bread_page, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_bread_page, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel13 = lv_obj_create(ui_breadrep);
    lv_obj_set_width(ui_Panel13, 696);
    lv_obj_set_height(ui_Panel13, 482);
    lv_obj_set_x(ui_Panel13, 60);
    lv_obj_set_y(ui_Panel13, 10);
    lv_obj_set_align(ui_Panel13, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel13, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel13, lv_color_hex(0xECE7D6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel13, lv_color_hex(0x0F00FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel13, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Panel13, LV_BORDER_SIDE_TOP, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_breadflourlab = lv_label_create(ui_Panel13);
    lv_obj_set_width(ui_breadflourlab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_breadflourlab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_breadflourlab, -128);
    lv_obj_set_y(ui_breadflourlab, -150);
    lv_obj_set_align(ui_breadflourlab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_breadflourlab, "FLOUR                 :");
    lv_obj_set_style_text_font(ui_breadflourlab, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_breadflourtext = lv_textarea_create(ui_Panel13);
    lv_obj_set_width(ui_breadflourtext, 212);
    lv_obj_set_height(ui_breadflourtext, 42);
    lv_obj_set_x(ui_breadflourtext, 82);
    lv_obj_set_y(ui_breadflourtext, -150);
    lv_obj_set_align(ui_breadflourtext, LV_ALIGN_CENTER);
    if("0,1,2,3,4,5,6,7,8,9,." == "") lv_textarea_set_accepted_chars(ui_breadflourtext, NULL);
    else lv_textarea_set_accepted_chars(ui_breadflourtext, "0,1,2,3,4,5,6,7,8,9,.");
    lv_textarea_set_max_length(ui_breadflourtext, 5);
    lv_textarea_set_text(ui_breadflourtext, "187.5");
    lv_textarea_set_placeholder_text(ui_breadflourtext, "Enter value in grams...");
    lv_obj_set_style_text_color(ui_breadflourtext, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_breadflourtext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_breadflourtext, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_breadflourtext, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_breadflourtext, lv_color_hex(0x4A3FFD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_breadflourtext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_breadflourtext, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_breadflourtext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_breadflourtext, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_breadflourtext, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_breadflourtext, lv_color_hex(0x8C8C8C), LV_PART_MAIN | LV_STATE_EDITED);
    lv_obj_set_style_bg_opa(ui_breadflourtext, 255, LV_PART_MAIN | LV_STATE_EDITED);
    lv_obj_set_style_text_color(ui_breadflourtext, lv_color_hex(0x050505), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_breadflourtext, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_color(ui_breadflourtext, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_breadflourtext, 255, LV_PART_MAIN | LV_STATE_FOCUSED);


    lv_obj_set_style_text_color(ui_breadflourtext, lv_color_hex(0xFFFFFF), LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_breadflourtext, 255, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_breadflourtext, lv_color_hex(0x050505), LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_breadflourtext, 255, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_FOCUSED);

    ui_breadsuglab = lv_label_create(ui_Panel13);
    lv_obj_set_width(ui_breadsuglab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_breadsuglab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_breadsuglab, -128);
    lv_obj_set_y(ui_breadsuglab, -50);
    lv_obj_set_align(ui_breadsuglab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_breadsuglab, "SUGAR                 :");
    lv_obj_set_style_text_font(ui_breadsuglab, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_breadBPlab = lv_label_create(ui_Panel13);
    lv_obj_set_width(ui_breadBPlab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_breadBPlab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_breadBPlab, -155);
    lv_obj_set_y(ui_breadBPlab, 50);
    lv_obj_set_align(ui_breadBPlab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_breadBPlab, "BAKING POWDER     :");
    lv_obj_set_style_text_font(ui_breadBPlab, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_breadsugtext = lv_textarea_create(ui_Panel13);
    lv_obj_set_width(ui_breadsugtext, 212);
    lv_obj_set_height(ui_breadsugtext, 42);
    lv_obj_set_x(ui_breadsugtext, 82);
    lv_obj_set_y(ui_breadsugtext, -50);
    lv_obj_set_align(ui_breadsugtext, LV_ALIGN_CENTER);
    if("0,1,2,3,4,5,6,7,8,9,." == "") lv_textarea_set_accepted_chars(ui_breadsugtext, NULL);
    else lv_textarea_set_accepted_chars(ui_breadsugtext, "0,1,2,3,4,5,6,7,8,9,.");
    lv_textarea_set_max_length(ui_breadsugtext, 5);
    lv_textarea_set_text(ui_breadsugtext, "15");
    lv_textarea_set_placeholder_text(ui_breadsugtext, "Enter value in grams...");
    lv_obj_set_style_text_color(ui_breadsugtext, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_breadsugtext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_breadsugtext, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_breadsugtext, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_breadsugtext, lv_color_hex(0x4A3FFD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_breadsugtext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_breadsugtext, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_breadsugtext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_breadsugtext, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_breadsugtext, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_breadsugtext, lv_color_hex(0x030303), LV_PART_MAIN | LV_STATE_EDITED);
    lv_obj_set_style_text_opa(ui_breadsugtext, 255, LV_PART_MAIN | LV_STATE_EDITED);
    lv_obj_set_style_text_color(ui_breadsugtext, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_breadsugtext, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_color(ui_breadsugtext, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_breadsugtext, 255, LV_PART_MAIN | LV_STATE_FOCUSED);


    lv_obj_set_style_text_color(ui_breadsugtext, lv_color_hex(0xFFFFFF), LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_breadsugtext, 255, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_breadsugtext, lv_color_hex(0x040404), LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_breadsugtext, 255, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_FOCUSED);

    ui_breadBPtext = lv_textarea_create(ui_Panel13);
    lv_obj_set_width(ui_breadBPtext, 212);
    lv_obj_set_height(ui_breadBPtext, 42);
    lv_obj_set_x(ui_breadBPtext, 83);
    lv_obj_set_y(ui_breadBPtext, 50);
    lv_obj_set_align(ui_breadBPtext, LV_ALIGN_CENTER);
    if("0,1,2,3,4,5,6,7,8,9,." == "") lv_textarea_set_accepted_chars(ui_breadBPtext, NULL);
    else lv_textarea_set_accepted_chars(ui_breadBPtext, "0,1,2,3,4,5,6,7,8,9,.");
    lv_textarea_set_max_length(ui_breadBPtext, 5);
    lv_textarea_set_text(ui_breadBPtext, "1.3");
    lv_textarea_set_placeholder_text(ui_breadBPtext, "Enter value in grams...");
    lv_obj_set_style_text_color(ui_breadBPtext, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_breadBPtext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_breadBPtext, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_breadBPtext, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_breadBPtext, lv_color_hex(0x4A3FFD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_breadBPtext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_breadBPtext, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_breadBPtext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_breadBPtext, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_breadBPtext, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_breadBPtext, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_breadBPtext, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_color(ui_breadBPtext, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_breadBPtext, 255, LV_PART_MAIN | LV_STATE_FOCUSED);


    lv_obj_set_style_text_color(ui_breadBPtext, lv_color_hex(0xFFFFFF), LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_breadBPtext, 255, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_breadBPtext, lv_color_hex(0x010101), LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_breadBPtext, 255, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_FOCUSED);

    ui_g_flour5 = lv_label_create(ui_Panel13);
    lv_obj_set_width(ui_g_flour5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_g_flour5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_g_flour5, 212);
    lv_obj_set_y(ui_g_flour5, -150);
    lv_obj_set_align(ui_g_flour5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_g_flour5, "g");

    ui_g_sug5 = lv_label_create(ui_Panel13);
    lv_obj_set_width(ui_g_sug5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_g_sug5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_g_sug5, 212);
    lv_obj_set_y(ui_g_sug5, -50);
    lv_obj_set_align(ui_g_sug5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_g_sug5, "g");

    ui_g_bp5 = lv_label_create(ui_Panel13);
    lv_obj_set_width(ui_g_bp5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_g_bp5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_g_bp5, 212);
    lv_obj_set_y(ui_g_bp5, 50);
    lv_obj_set_align(ui_g_bp5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_g_bp5, "g");

    ui_Panel14 = lv_obj_create(ui_Panel13);
    lv_obj_set_width(ui_Panel14, 62);
    lv_obj_set_height(ui_Panel14, 217);
    lv_obj_set_x(ui_Panel14, -213);
    lv_obj_set_y(ui_Panel14, -176);
    lv_obj_set_align(ui_Panel14, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel14, lv_color_hex(0x8C8C8C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel14, lv_color_hex(0x0F00FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel14, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_angle(ui_Panel14, 450, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label18 = lv_label_create(ui_Panel14);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label18, 41);
    lv_obj_set_y(ui_Label18, 74);
    lv_obj_set_align(ui_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label18, "BREAD");
    lv_obj_set_style_text_color(ui_Label18, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label18, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label18, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_angle(ui_Label18, -900, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_breadconfirm = lv_imgbtn_create(ui_breadrep);
    lv_imgbtn_set_src(ui_breadconfirm, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_confirm_icon_png, NULL);
    lv_imgbtn_set_src(ui_breadconfirm, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_confirm_icon_png, NULL);
    lv_imgbtn_set_src(ui_breadconfirm, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_breadconfirm, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_breadconfirm, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_breadconfirm, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_height(ui_breadconfirm, 64);
    lv_obj_set_width(ui_breadconfirm, LV_SIZE_CONTENT);   /// -137
    lv_obj_set_x(ui_breadconfirm, -340);
    lv_obj_set_y(ui_breadconfirm, 150);
    lv_obj_set_align(ui_breadconfirm, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_breadconfirm, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_breadconfirm, lv_color_hex(0x36FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_breadconfirm, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_breadconfirm, lv_color_hex(0x0F00FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_breadconfirm, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_breadkeyboard = lv_keyboard_create(ui_breadrep);
    lv_keyboard_set_mode(ui_breadkeyboard, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_width(ui_breadkeyboard, 673);
    lv_obj_set_height(ui_breadkeyboard, 228);
    lv_obj_set_x(ui_breadkeyboard, 55);
    lv_obj_set_y(ui_breadkeyboard, 97);
    lv_obj_set_align(ui_breadkeyboard, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_breadkeyboard, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_radius(ui_breadkeyboard, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_breadkeyboard, lv_color_hex(0x5C5C5C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_breadkeyboard, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_breadkeyboard, 100, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_breadkeyboard, lv_color_hex(0x4A3FFD), LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_breadkeyboard, 255, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_breadkeyboard, lv_color_hex(0x000000), LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_breadkeyboard, 255, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_breadkeyboard, 1, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_breadkeyboard, LV_BORDER_SIDE_FULL, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_breadkeyboard, lv_color_hex(0xFFFFFF), LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_breadkeyboard, 255, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_breadkeyboard, &lv_font_montserrat_20, LV_PART_ITEMS | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_bread_rep, ui_event_bread_rep, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_bread_home, ui_event_bread_home, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_breadflourtext, ui_event_breadflourtext, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_breadsugtext, ui_event_breadsugtext, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_breadBPtext, ui_event_breadBPtext, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_breadconfirm, ui_event_breadconfirm, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_breadkeyboard, ui_breadflourtext);
    lv_obj_add_event_cb(ui_breadrep, ui_event_breadrep, LV_EVENT_ALL, NULL);

}
