// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_brownrep_screen_init(void)
{
    ui_brownrep = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_brownrep, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_brownrep, lv_color_hex(0x454444), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_brownrep, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_brownrep, lv_color_hex(0x6E6E6E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_brownrep, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_brownrep, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_brownrep, LV_BORDER_SIDE_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_brown_rep = lv_imgbtn_create(ui_brownrep);
    lv_imgbtn_set_src(ui_brown_rep, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_kitchen_whisk_icon_png, NULL);
    lv_imgbtn_set_src(ui_brown_rep, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_kitchen_whisk_icon_png, NULL);
    lv_imgbtn_set_src(ui_brown_rep, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_brown_rep, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_brown_rep, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_brown_rep, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_height(ui_brown_rep, 72);
    lv_obj_set_width(ui_brown_rep, LV_SIZE_CONTENT);   /// -137
    lv_obj_set_x(ui_brown_rep, -340);
    lv_obj_set_y(ui_brown_rep, -80);
    lv_obj_set_align(ui_brown_rep, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_brown_rep, lv_color_hex(0x6E6E6E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_brown_rep, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_brown_rep, lv_color_hex(0x0F00FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_brown_rep, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_brown_home = lv_imgbtn_create(ui_brownrep);
    lv_imgbtn_set_src(ui_brown_home, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_home_icon_png, NULL);
    lv_imgbtn_set_src(ui_brown_home, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_home_icon_png, NULL);
    lv_imgbtn_set_src(ui_brown_home, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_brown_home, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_brown_home, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_brown_home, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_height(ui_brown_home, 79);
    lv_obj_set_width(ui_brown_home, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_brown_home, -347);
    lv_obj_set_y(ui_brown_home, -191);
    lv_obj_set_align(ui_brown_home, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_brown_home, lv_color_hex(0x6E6E6E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_brown_home, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_brown_page = lv_imgbtn_create(ui_brownrep);
    lv_imgbtn_set_src(ui_brown_page, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_chocolate_bar_icon_png, NULL);
    lv_imgbtn_set_src(ui_brown_page, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_chocolate_bar_icon_png, NULL);
    lv_imgbtn_set_src(ui_brown_page, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_brown_page, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_brown_page, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_brown_page, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_brown_page, 80);
    lv_obj_set_height(ui_brown_page, 67);
    lv_obj_set_x(ui_brown_page, -318);
    lv_obj_set_y(ui_brown_page, 25);
    lv_obj_set_align(ui_brown_page, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_brown_page, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_brown_page, lv_color_hex(0x00FEFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_brown_page, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_brown_page, lv_color_hex(0x00FEFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_brown_page, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_brown_page, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_brown_page, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_brown_page, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_brown_page, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_brown_page, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_brown_page, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel9 = lv_obj_create(ui_brownrep);
    lv_obj_set_width(ui_Panel9, 696);
    lv_obj_set_height(ui_Panel9, 482);
    lv_obj_set_x(ui_Panel9, 60);
    lv_obj_set_y(ui_Panel9, 10);
    lv_obj_set_align(ui_Panel9, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel9, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel9, lv_color_hex(0xECE7D6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel9, lv_color_hex(0x00FEFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel9, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Panel9, LV_BORDER_SIDE_TOP, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_brownflourlab = lv_label_create(ui_Panel9);
    lv_obj_set_width(ui_brownflourlab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_brownflourlab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_brownflourlab, -128);
    lv_obj_set_y(ui_brownflourlab, -150);
    lv_obj_set_align(ui_brownflourlab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_brownflourlab, "FLOUR                 :");
    lv_obj_set_style_text_font(ui_brownflourlab, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_brownflourtext1 = lv_textarea_create(ui_Panel9);
    lv_obj_set_width(ui_brownflourtext1, 212);
    lv_obj_set_height(ui_brownflourtext1, 42);
    lv_obj_set_x(ui_brownflourtext1, 82);
    lv_obj_set_y(ui_brownflourtext1, -150);
    lv_obj_set_align(ui_brownflourtext1, LV_ALIGN_CENTER);
    if("0,1,2,3,4,5,6,7,8,9,." == "") lv_textarea_set_accepted_chars(ui_brownflourtext1, NULL);
    else lv_textarea_set_accepted_chars(ui_brownflourtext1, "0,1,2,3,4,5,6,7,8,9,.");
    lv_textarea_set_max_length(ui_brownflourtext1, 5);
    lv_textarea_set_text(ui_brownflourtext1, "375");
    lv_textarea_set_placeholder_text(ui_brownflourtext1, "Enter value in grams...");
    lv_obj_set_style_text_color(ui_brownflourtext1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_brownflourtext1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_brownflourtext1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_brownflourtext1, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_brownflourtext1, lv_color_hex(0x77FEFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_brownflourtext1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_brownflourtext1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_brownflourtext1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_brownflourtext1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_brownflourtext1, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_brownflourtext1, lv_color_hex(0x8C8C8C), LV_PART_MAIN | LV_STATE_EDITED);
    lv_obj_set_style_bg_opa(ui_brownflourtext1, 255, LV_PART_MAIN | LV_STATE_EDITED);
    lv_obj_set_style_text_color(ui_brownflourtext1, lv_color_hex(0x050505), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_brownflourtext1, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_color(ui_brownflourtext1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_brownflourtext1, 255, LV_PART_MAIN | LV_STATE_FOCUSED);


    lv_obj_set_style_text_color(ui_brownflourtext1, lv_color_hex(0x000000),
                                LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_brownflourtext1, 255, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_brownflourtext1, lv_color_hex(0x050505),
                                LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_brownflourtext1, 255, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_FOCUSED);

    ui_brownsuglab1 = lv_label_create(ui_Panel9);
    lv_obj_set_width(ui_brownsuglab1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_brownsuglab1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_brownsuglab1, -128);
    lv_obj_set_y(ui_brownsuglab1, -50);
    lv_obj_set_align(ui_brownsuglab1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_brownsuglab1, "SUGAR                 :");
    lv_obj_set_style_text_font(ui_brownsuglab1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_brownBPlab1 = lv_label_create(ui_Panel9);
    lv_obj_set_width(ui_brownBPlab1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_brownBPlab1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_brownBPlab1, -155);
    lv_obj_set_y(ui_brownBPlab1, 50);
    lv_obj_set_align(ui_brownBPlab1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_brownBPlab1, "BAKING POWDER     :");
    lv_obj_set_style_text_font(ui_brownBPlab1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_brownsugtext1 = lv_textarea_create(ui_Panel9);
    lv_obj_set_width(ui_brownsugtext1, 212);
    lv_obj_set_height(ui_brownsugtext1, 42);
    lv_obj_set_x(ui_brownsugtext1, 82);
    lv_obj_set_y(ui_brownsugtext1, -50);
    lv_obj_set_align(ui_brownsugtext1, LV_ALIGN_CENTER);
    if("0,1,2,3,4,5,6,7,8,9,." == "") lv_textarea_set_accepted_chars(ui_brownsugtext1, NULL);
    else lv_textarea_set_accepted_chars(ui_brownsugtext1, "0,1,2,3,4,5,6,7,8,9,.");
    lv_textarea_set_max_length(ui_brownsugtext1, 5);
    lv_textarea_set_text(ui_brownsugtext1, "500");
    lv_textarea_set_placeholder_text(ui_brownsugtext1, "Enter value in grams...");
    lv_obj_set_style_text_color(ui_brownsugtext1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_brownsugtext1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_brownsugtext1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_brownsugtext1, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_brownsugtext1, lv_color_hex(0x77FEFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_brownsugtext1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_brownsugtext1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_brownsugtext1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_brownsugtext1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_brownsugtext1, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_brownsugtext1, lv_color_hex(0x030303), LV_PART_MAIN | LV_STATE_EDITED);
    lv_obj_set_style_text_opa(ui_brownsugtext1, 255, LV_PART_MAIN | LV_STATE_EDITED);
    lv_obj_set_style_bg_color(ui_brownsugtext1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_brownsugtext1, 255, LV_PART_MAIN | LV_STATE_FOCUSED);


    lv_obj_set_style_text_color(ui_brownsugtext1, lv_color_hex(0x000000), LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_brownsugtext1, 255, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_brownsugtext1, lv_color_hex(0x040404), LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_brownsugtext1, 255, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_FOCUSED);

    ui_brownBPtext1 = lv_textarea_create(ui_Panel9);
    lv_obj_set_width(ui_brownBPtext1, 212);
    lv_obj_set_height(ui_brownBPtext1, 42);
    lv_obj_set_x(ui_brownBPtext1, 83);
    lv_obj_set_y(ui_brownBPtext1, 50);
    lv_obj_set_align(ui_brownBPtext1, LV_ALIGN_CENTER);
    if("0,1,2,3,4,5,6,7,8,9,." == "") lv_textarea_set_accepted_chars(ui_brownBPtext1, NULL);
    else lv_textarea_set_accepted_chars(ui_brownBPtext1, "0,1,2,3,4,5,6,7,8,9,.");
    lv_textarea_set_max_length(ui_brownBPtext1, 5);
    lv_textarea_set_text(ui_brownBPtext1, "2.5");
    lv_textarea_set_placeholder_text(ui_brownBPtext1, "Enter value in grams...");
    lv_obj_set_style_text_color(ui_brownBPtext1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_brownBPtext1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_brownBPtext1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_brownBPtext1, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_brownBPtext1, lv_color_hex(0x77FEFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_brownBPtext1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_brownBPtext1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_brownBPtext1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_brownBPtext1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_brownBPtext1, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_brownBPtext1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_brownBPtext1, 255, LV_PART_MAIN | LV_STATE_FOCUSED);


    lv_obj_set_style_text_color(ui_brownBPtext1, lv_color_hex(0x000000), LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_brownBPtext1, 255, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_brownBPtext1, lv_color_hex(0x010101), LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_brownBPtext1, 255, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_FOCUSED);

    ui_brownCPlab1 = lv_label_create(ui_Panel9);
    lv_obj_set_width(ui_brownCPlab1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_brownCPlab1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_brownCPlab1, -155);
    lv_obj_set_y(ui_brownCPlab1, 150);
    lv_obj_set_align(ui_brownCPlab1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_brownCPlab1, "COCOA POWDER     :");
    lv_obj_set_style_text_font(ui_brownCPlab1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_brownCPtext1 = lv_textarea_create(ui_Panel9);
    lv_obj_set_width(ui_brownCPtext1, 212);
    lv_obj_set_height(ui_brownCPtext1, 42);
    lv_obj_set_x(ui_brownCPtext1, 83);
    lv_obj_set_y(ui_brownCPtext1, 150);
    lv_obj_set_align(ui_brownCPtext1, LV_ALIGN_CENTER);
    if("0,1,2,3,4,5,6,7,8,9,." == "") lv_textarea_set_accepted_chars(ui_brownCPtext1, NULL);
    else lv_textarea_set_accepted_chars(ui_brownCPtext1, "0,1,2,3,4,5,6,7,8,9,.");
    lv_textarea_set_max_length(ui_brownCPtext1, 5);
    lv_textarea_set_text(ui_brownCPtext1, "125");
    lv_textarea_set_placeholder_text(ui_brownCPtext1, "Enter value in grams...");
    lv_obj_set_style_text_color(ui_brownCPtext1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_brownCPtext1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_brownCPtext1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_brownCPtext1, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_brownCPtext1, lv_color_hex(0x77FEFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_brownCPtext1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_brownCPtext1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_brownCPtext1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_brownCPtext1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_brownCPtext1, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_brownCPtext1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_brownCPtext1, 255, LV_PART_MAIN | LV_STATE_FOCUSED);


    lv_obj_set_style_text_color(ui_brownCPtext1, lv_color_hex(0x000000), LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_brownCPtext1, 255, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_brownCPtext1, lv_color_hex(0x000000), LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_brownCPtext1, 255, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_FOCUSED);

    ui_g_flour3 = lv_label_create(ui_Panel9);
    lv_obj_set_width(ui_g_flour3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_g_flour3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_g_flour3, 212);
    lv_obj_set_y(ui_g_flour3, -150);
    lv_obj_set_align(ui_g_flour3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_g_flour3, "g");

    ui_g_sug3 = lv_label_create(ui_Panel9);
    lv_obj_set_width(ui_g_sug3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_g_sug3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_g_sug3, 212);
    lv_obj_set_y(ui_g_sug3, -50);
    lv_obj_set_align(ui_g_sug3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_g_sug3, "g");

    ui_g_bp3 = lv_label_create(ui_Panel9);
    lv_obj_set_width(ui_g_bp3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_g_bp3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_g_bp3, 212);
    lv_obj_set_y(ui_g_bp3, 50);
    lv_obj_set_align(ui_g_bp3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_g_bp3, "g");

    ui_g_cp3 = lv_label_create(ui_Panel9);
    lv_obj_set_width(ui_g_cp3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_g_cp3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_g_cp3, 212);
    lv_obj_set_y(ui_g_cp3, 150);
    lv_obj_set_align(ui_g_cp3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_g_cp3, "g");

    ui_Panel10 = lv_obj_create(ui_Panel9);
    lv_obj_set_width(ui_Panel10, 62);
    lv_obj_set_height(ui_Panel10, 217);
    lv_obj_set_x(ui_Panel10, -213);
    lv_obj_set_y(ui_Panel10, -176);
    lv_obj_set_align(ui_Panel10, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel10, lv_color_hex(0x8C8C8C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel10, lv_color_hex(0x00FEFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel10, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_angle(ui_Panel10, 450, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label16 = lv_label_create(ui_Panel10);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label16, 49);
    lv_obj_set_y(ui_Label16, 69);
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, "BROWNIES");
    lv_obj_set_style_text_color(ui_Label16, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label16, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_angle(ui_Label16, -900, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_brownconfirm = lv_imgbtn_create(ui_brownrep);
    lv_imgbtn_set_src(ui_brownconfirm, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_confirm_icon_png, NULL);
    lv_imgbtn_set_src(ui_brownconfirm, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_confirm_icon_png, NULL);
    lv_imgbtn_set_src(ui_brownconfirm, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_brownconfirm, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_brownconfirm, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_brownconfirm, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_height(ui_brownconfirm, 64);
    lv_obj_set_width(ui_brownconfirm, LV_SIZE_CONTENT);   /// -137
    lv_obj_set_x(ui_brownconfirm, -340);
    lv_obj_set_y(ui_brownconfirm, 150);
    lv_obj_set_align(ui_brownconfirm, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_brownconfirm, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_brownconfirm, lv_color_hex(0x36FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_brownconfirm, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_brownconfirm, lv_color_hex(0x0F00FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_brownconfirm, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_brownkeyboard = lv_keyboard_create(ui_brownrep);
    lv_keyboard_set_mode(ui_brownkeyboard, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_width(ui_brownkeyboard, 673);
    lv_obj_set_height(ui_brownkeyboard, 228);
    lv_obj_set_x(ui_brownkeyboard, 55);
    lv_obj_set_y(ui_brownkeyboard, 97);
    lv_obj_set_align(ui_brownkeyboard, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_brownkeyboard, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_radius(ui_brownkeyboard, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_brownkeyboard, lv_color_hex(0x5C5C5C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_brownkeyboard, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_brownkeyboard, 100, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_brownkeyboard, lv_color_hex(0x00FEFF), LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_brownkeyboard, 255, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_brownkeyboard, lv_color_hex(0x000000), LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_brownkeyboard, 255, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_brownkeyboard, 1, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_brownkeyboard, LV_BORDER_SIDE_FULL, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_brownkeyboard, &lv_font_montserrat_20, LV_PART_ITEMS | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_brown_rep, ui_event_brown_rep, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_brown_home, ui_event_brown_home, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_brownflourtext1, ui_event_brownflourtext1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_brownsugtext1, ui_event_brownsugtext1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_brownBPtext1, ui_event_brownBPtext1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_brownCPtext1, ui_event_brownCPtext1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_brownconfirm, ui_event_brownconfirm, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_brownkeyboard, ui_brownflourtext1);
    lv_obj_add_event_cb(ui_brownrep, ui_event_brownrep, LV_EVENT_ALL, NULL);

}
