// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_cookrep_screen_init(void)
{
    ui_cookrep = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_cookrep, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_cookrep, lv_color_hex(0x454444), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cookrep, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_cookrep, lv_color_hex(0x6E6E6E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_cookrep, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_cookrep, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_cookrep, LV_BORDER_SIDE_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cook_rep = lv_imgbtn_create(ui_cookrep);
    lv_imgbtn_set_src(ui_cook_rep, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_kitchen_whisk_icon_png, NULL);
    lv_imgbtn_set_src(ui_cook_rep, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_kitchen_whisk_icon_png, NULL);
    lv_imgbtn_set_src(ui_cook_rep, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_cook_rep, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_cook_rep, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_cook_rep, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_height(ui_cook_rep, 72);
    lv_obj_set_width(ui_cook_rep, LV_SIZE_CONTENT);   /// -137
    lv_obj_set_x(ui_cook_rep, -340);
    lv_obj_set_y(ui_cook_rep, -80);
    lv_obj_set_align(ui_cook_rep, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_cook_rep, lv_color_hex(0x6E6E6E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cook_rep, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_cook_rep, lv_color_hex(0x0F00FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_cook_rep, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cook_home = lv_imgbtn_create(ui_cookrep);
    lv_imgbtn_set_src(ui_cook_home, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_home_icon_png, NULL);
    lv_imgbtn_set_src(ui_cook_home, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_home_icon_png, NULL);
    lv_imgbtn_set_src(ui_cook_home, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_cook_home, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_cook_home, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_cook_home, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_height(ui_cook_home, 79);
    lv_obj_set_width(ui_cook_home, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_cook_home, -347);
    lv_obj_set_y(ui_cook_home, -191);
    lv_obj_set_align(ui_cook_home, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_cook_home, lv_color_hex(0x6E6E6E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cook_home, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cook_page = lv_imgbtn_create(ui_cookrep);
    lv_imgbtn_set_src(ui_cook_page, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_cookie_half_icon_png, NULL);
    lv_imgbtn_set_src(ui_cook_page, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_cookie_half_icon_png, NULL);
    lv_imgbtn_set_src(ui_cook_page, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_cook_page, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_cook_page, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_cook_page, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_cook_page, 80);
    lv_obj_set_height(ui_cook_page, 74);
    lv_obj_set_x(ui_cook_page, -318);
    lv_obj_set_y(ui_cook_page, 25);
    lv_obj_set_align(ui_cook_page, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_cook_page, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_cook_page, lv_color_hex(0x00FFA6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cook_page, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_cook_page, lv_color_hex(0x00FFA6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_cook_page, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_cook_page, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_cook_page, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_cook_page, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_cook_page, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_cook_page, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_cook_page, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel5 = lv_obj_create(ui_cookrep);
    lv_obj_set_width(ui_Panel5, 696);
    lv_obj_set_height(ui_Panel5, 482);
    lv_obj_set_x(ui_Panel5, 60);
    lv_obj_set_y(ui_Panel5, 10);
    lv_obj_set_align(ui_Panel5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel5, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel5, lv_color_hex(0xECE7D6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel5, lv_color_hex(0x00FFA6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel5, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Panel5, LV_BORDER_SIDE_TOP, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cookflourlab = lv_label_create(ui_Panel5);
    lv_obj_set_width(ui_cookflourlab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_cookflourlab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_cookflourlab, -128);
    lv_obj_set_y(ui_cookflourlab, -150);
    lv_obj_set_align(ui_cookflourlab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_cookflourlab, "FLOUR                 :");
    lv_obj_set_style_text_font(ui_cookflourlab, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cookflourtext = lv_textarea_create(ui_Panel5);
    lv_obj_set_width(ui_cookflourtext, 212);
    lv_obj_set_height(ui_cookflourtext, 42);
    lv_obj_set_x(ui_cookflourtext, 82);
    lv_obj_set_y(ui_cookflourtext, -150);
    lv_obj_set_align(ui_cookflourtext, LV_ALIGN_CENTER);
    if("0,1,2,3,4,5,6,7,8,9,." == "") lv_textarea_set_accepted_chars(ui_cookflourtext, NULL);
    else lv_textarea_set_accepted_chars(ui_cookflourtext, "0,1,2,3,4,5,6,7,8,9,.");
    lv_textarea_set_max_length(ui_cookflourtext, 5);
    lv_textarea_set_text(ui_cookflourtext, "300");
    lv_textarea_set_placeholder_text(ui_cookflourtext, "Enter value in grams...");
    lv_obj_set_style_text_color(ui_cookflourtext, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_cookflourtext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_cookflourtext, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_cookflourtext, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_cookflourtext, lv_color_hex(0x74FBCC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cookflourtext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_cookflourtext, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_cookflourtext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_cookflourtext, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_cookflourtext, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_cookflourtext, lv_color_hex(0x8C8C8C), LV_PART_MAIN | LV_STATE_EDITED);
    lv_obj_set_style_bg_opa(ui_cookflourtext, 255, LV_PART_MAIN | LV_STATE_EDITED);
    lv_obj_set_style_text_color(ui_cookflourtext, lv_color_hex(0x050505), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_cookflourtext, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_color(ui_cookflourtext, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_cookflourtext, 255, LV_PART_MAIN | LV_STATE_FOCUSED);


    lv_obj_set_style_text_color(ui_cookflourtext, lv_color_hex(0x000000), LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_cookflourtext, 255, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_cookflourtext, lv_color_hex(0x050505), LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_cookflourtext, 255, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_FOCUSED);

    ui_cooksuglab = lv_label_create(ui_Panel5);
    lv_obj_set_width(ui_cooksuglab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_cooksuglab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_cooksuglab, -128);
    lv_obj_set_y(ui_cooksuglab, -50);
    lv_obj_set_align(ui_cooksuglab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_cooksuglab, "SUGAR                 :");
    lv_obj_set_style_text_font(ui_cooksuglab, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cookBPlab = lv_label_create(ui_Panel5);
    lv_obj_set_width(ui_cookBPlab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_cookBPlab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_cookBPlab, -155);
    lv_obj_set_y(ui_cookBPlab, 50);
    lv_obj_set_align(ui_cookBPlab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_cookBPlab, "BAKING POWDER     :");
    lv_obj_set_style_text_font(ui_cookBPlab, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cooksugtext = lv_textarea_create(ui_Panel5);
    lv_obj_set_width(ui_cooksugtext, 212);
    lv_obj_set_height(ui_cooksugtext, 42);
    lv_obj_set_x(ui_cooksugtext, 82);
    lv_obj_set_y(ui_cooksugtext, -50);
    lv_obj_set_align(ui_cooksugtext, LV_ALIGN_CENTER);
    if("0,1,2,3,4,5,6,7,8,9,." == "") lv_textarea_set_accepted_chars(ui_cooksugtext, NULL);
    else lv_textarea_set_accepted_chars(ui_cooksugtext, "0,1,2,3,4,5,6,7,8,9,.");
    lv_textarea_set_max_length(ui_cooksugtext, 5);
    lv_textarea_set_text(ui_cooksugtext, "300");
    lv_textarea_set_placeholder_text(ui_cooksugtext, "Enter value in grams...");
    lv_obj_set_style_text_color(ui_cooksugtext, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_cooksugtext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_cooksugtext, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_cooksugtext, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_cooksugtext, lv_color_hex(0x74FBCC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cooksugtext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_cooksugtext, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_cooksugtext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_cooksugtext, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_cooksugtext, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_cooksugtext, lv_color_hex(0x030303), LV_PART_MAIN | LV_STATE_EDITED);
    lv_obj_set_style_text_opa(ui_cooksugtext, 255, LV_PART_MAIN | LV_STATE_EDITED);
    lv_obj_set_style_bg_color(ui_cooksugtext, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_cooksugtext, 255, LV_PART_MAIN | LV_STATE_FOCUSED);


    lv_obj_set_style_text_color(ui_cooksugtext, lv_color_hex(0x000000), LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_cooksugtext, 255, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_cooksugtext, lv_color_hex(0x040404), LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_cooksugtext, 255, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_FOCUSED);

    ui_cookBPtext = lv_textarea_create(ui_Panel5);
    lv_obj_set_width(ui_cookBPtext, 212);
    lv_obj_set_height(ui_cookBPtext, 42);
    lv_obj_set_x(ui_cookBPtext, 83);
    lv_obj_set_y(ui_cookBPtext, 50);
    lv_obj_set_align(ui_cookBPtext, LV_ALIGN_CENTER);
    if("0,1,2,3,4,5,6,7,8,9,." == "") lv_textarea_set_accepted_chars(ui_cookBPtext, NULL);
    else lv_textarea_set_accepted_chars(ui_cookBPtext, "0,1,2,3,4,5,6,7,8,9,.");
    lv_textarea_set_max_length(ui_cookBPtext, 5);
    lv_textarea_set_text(ui_cookBPtext, "3.7");
    lv_textarea_set_placeholder_text(ui_cookBPtext, "Enter value in grams...");
    lv_obj_set_style_text_color(ui_cookBPtext, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_cookBPtext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_cookBPtext, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_cookBPtext, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_cookBPtext, lv_color_hex(0x74FBCC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cookBPtext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_cookBPtext, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_cookBPtext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_cookBPtext, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_cookBPtext, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_cookBPtext, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_cookBPtext, 255, LV_PART_MAIN | LV_STATE_FOCUSED);


    lv_obj_set_style_text_color(ui_cookBPtext, lv_color_hex(0x000000), LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_cookBPtext, 255, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_cookBPtext, lv_color_hex(0x010101), LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_cookBPtext, 255, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_FOCUSED);

    ui_cookCPlab = lv_label_create(ui_Panel5);
    lv_obj_set_width(ui_cookCPlab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_cookCPlab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_cookCPlab, -155);
    lv_obj_set_y(ui_cookCPlab, 150);
    lv_obj_set_align(ui_cookCPlab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_cookCPlab, "COCOA POWDER     :");
    lv_obj_set_style_text_font(ui_cookCPlab, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cookCPtext = lv_textarea_create(ui_Panel5);
    lv_obj_set_width(ui_cookCPtext, 212);
    lv_obj_set_height(ui_cookCPtext, 42);
    lv_obj_set_x(ui_cookCPtext, 83);
    lv_obj_set_y(ui_cookCPtext, 150);
    lv_obj_set_align(ui_cookCPtext, LV_ALIGN_CENTER);
    if("0,1,2,3,4,5,6,7,8,9,." == "") lv_textarea_set_accepted_chars(ui_cookCPtext, NULL);
    else lv_textarea_set_accepted_chars(ui_cookCPtext, "0,1,2,3,4,5,6,7,8,9,.");
    lv_textarea_set_max_length(ui_cookCPtext, 5);
    lv_textarea_set_text(ui_cookCPtext, "50");
    lv_textarea_set_placeholder_text(ui_cookCPtext, "Enter value in grams...");
    lv_obj_set_style_text_color(ui_cookCPtext, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_cookCPtext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_cookCPtext, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_cookCPtext, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_cookCPtext, lv_color_hex(0x74FBCC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cookCPtext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_cookCPtext, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_cookCPtext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_cookCPtext, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_cookCPtext, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_cookCPtext, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_cookCPtext, 255, LV_PART_MAIN | LV_STATE_FOCUSED);


    lv_obj_set_style_text_color(ui_cookCPtext, lv_color_hex(0x000000), LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_cookCPtext, 255, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_cookCPtext, lv_color_hex(0x000000), LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_cookCPtext, 255, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_FOCUSED);

    ui_g_flour2 = lv_label_create(ui_Panel5);
    lv_obj_set_width(ui_g_flour2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_g_flour2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_g_flour2, 212);
    lv_obj_set_y(ui_g_flour2, -150);
    lv_obj_set_align(ui_g_flour2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_g_flour2, "g");

    ui_g_sug2 = lv_label_create(ui_Panel5);
    lv_obj_set_width(ui_g_sug2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_g_sug2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_g_sug2, 212);
    lv_obj_set_y(ui_g_sug2, -50);
    lv_obj_set_align(ui_g_sug2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_g_sug2, "g");

    ui_g_bp2 = lv_label_create(ui_Panel5);
    lv_obj_set_width(ui_g_bp2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_g_bp2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_g_bp2, 212);
    lv_obj_set_y(ui_g_bp2, 50);
    lv_obj_set_align(ui_g_bp2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_g_bp2, "g");

    ui_g_cp2 = lv_label_create(ui_Panel5);
    lv_obj_set_width(ui_g_cp2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_g_cp2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_g_cp2, 212);
    lv_obj_set_y(ui_g_cp2, 150);
    lv_obj_set_align(ui_g_cp2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_g_cp2, "g");

    ui_Panel8 = lv_obj_create(ui_Panel5);
    lv_obj_set_width(ui_Panel8, 62);
    lv_obj_set_height(ui_Panel8, 217);
    lv_obj_set_x(ui_Panel8, -213);
    lv_obj_set_y(ui_Panel8, -176);
    lv_obj_set_align(ui_Panel8, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel8, lv_color_hex(0x8C8C8C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel8, lv_color_hex(0x00FFA6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel8, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_angle(ui_Panel8, 450, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label15 = lv_label_create(ui_Panel8);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label15, 36);
    lv_obj_set_y(ui_Label15, 57);
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "COOKIES");
    lv_obj_set_style_text_color(ui_Label15, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label15, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_angle(ui_Label15, -900, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cookconfirm = lv_imgbtn_create(ui_cookrep);
    lv_imgbtn_set_src(ui_cookconfirm, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_confirm_icon_png, NULL);
    lv_imgbtn_set_src(ui_cookconfirm, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_confirm_icon_png, NULL);
    lv_imgbtn_set_src(ui_cookconfirm, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_cookconfirm, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_cookconfirm, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_cookconfirm, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_height(ui_cookconfirm, 64);
    lv_obj_set_width(ui_cookconfirm, LV_SIZE_CONTENT);   /// -137
    lv_obj_set_x(ui_cookconfirm, -340);
    lv_obj_set_y(ui_cookconfirm, 150);
    lv_obj_set_align(ui_cookconfirm, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_cookconfirm, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_cookconfirm, lv_color_hex(0x36FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cookconfirm, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_cookconfirm, lv_color_hex(0x0F00FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_cookconfirm, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cookkeyboard1 = lv_keyboard_create(ui_cookrep);
    lv_keyboard_set_mode(ui_cookkeyboard1, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_width(ui_cookkeyboard1, 673);
    lv_obj_set_height(ui_cookkeyboard1, 228);
    lv_obj_set_x(ui_cookkeyboard1, 55);
    lv_obj_set_y(ui_cookkeyboard1, 97);
    lv_obj_set_align(ui_cookkeyboard1, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_cookkeyboard1, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_radius(ui_cookkeyboard1, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_cookkeyboard1, lv_color_hex(0x5C5C5C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cookkeyboard1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_cookkeyboard1, 100, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_cookkeyboard1, lv_color_hex(0x00FFA6), LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cookkeyboard1, 255, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_cookkeyboard1, lv_color_hex(0x000000), LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_cookkeyboard1, 255, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_cookkeyboard1, 1, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_cookkeyboard1, LV_BORDER_SIDE_FULL, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_cookkeyboard1, &lv_font_montserrat_20, LV_PART_ITEMS | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_cook_rep, ui_event_cook_rep, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_cook_home, ui_event_cook_home, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_cookflourtext, ui_event_cookflourtext, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_cooksugtext, ui_event_cooksugtext, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_cookBPtext, ui_event_cookBPtext, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_cookCPtext, ui_event_cookCPtext, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_cookconfirm, ui_event_cookconfirm, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_cookkeyboard1, ui_cakeflourtext);
    lv_obj_add_event_cb(ui_cookrep, ui_event_cookrep, LV_EVENT_ALL, NULL);

}
