// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_custom3rep_screen_init(void)
{
    ui_custom3rep = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_custom3rep, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_custom3rep, lv_color_hex(0x454444), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_custom3rep, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_custom3rep, lv_color_hex(0x6E6E6E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_custom3rep, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_custom3rep, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_custom3rep, LV_BORDER_SIDE_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cus3_recipe = lv_imgbtn_create(ui_custom3rep);
    lv_imgbtn_set_src(ui_cus3_recipe, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_kitchen_whisk_icon_png, NULL);
    lv_imgbtn_set_src(ui_cus3_recipe, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_kitchen_whisk_icon_png, NULL);
    lv_imgbtn_set_src(ui_cus3_recipe, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_cus3_recipe, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_cus3_recipe, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_cus3_recipe, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_height(ui_cus3_recipe, 72);
    lv_obj_set_width(ui_cus3_recipe, LV_SIZE_CONTENT);   /// -137
    lv_obj_set_x(ui_cus3_recipe, -340);
    lv_obj_set_y(ui_cus3_recipe, -80);
    lv_obj_set_align(ui_cus3_recipe, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_cus3_recipe, lv_color_hex(0x6E6E6E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cus3_recipe, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_cus3_recipe, lv_color_hex(0x0F00FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_cus3_recipe, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cus3_home = lv_imgbtn_create(ui_custom3rep);
    lv_imgbtn_set_src(ui_cus3_home, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_home_icon_png, NULL);
    lv_imgbtn_set_src(ui_cus3_home, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_home_icon_png, NULL);
    lv_imgbtn_set_src(ui_cus3_home, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_cus3_home, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_cus3_home, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_cus3_home, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_height(ui_cus3_home, 79);
    lv_obj_set_width(ui_cus3_home, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_cus3_home, -347);
    lv_obj_set_y(ui_cus3_home, -191);
    lv_obj_set_align(ui_cus3_home, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_cus3_home, lv_color_hex(0x6E6E6E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cus3_home, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cus3_page = lv_imgbtn_create(ui_custom3rep);
    lv_imgbtn_set_src(ui_cus3_page, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_add_circle_png, NULL);
    lv_imgbtn_set_src(ui_cus3_page, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_add_circle_png, NULL);
    lv_imgbtn_set_src(ui_cus3_page, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_cus3_page, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_cus3_page, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_cus3_page, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_cus3_page, 80);
    lv_obj_set_height(ui_cus3_page, 74);
    lv_obj_set_x(ui_cus3_page, -318);
    lv_obj_set_y(ui_cus3_page, 25);
    lv_obj_set_align(ui_cus3_page, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_cus3_page, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_cus3_page, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cus3_page, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_cus3_page, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_cus3_page, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_cus3_page, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_cus3_page, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_cus3_page, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_cus3_page, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_cus3_page, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_cus3_page, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cus3panel = lv_obj_create(ui_custom3rep);
    lv_obj_set_width(ui_cus3panel, 696);
    lv_obj_set_height(ui_cus3panel, 482);
    lv_obj_set_x(ui_cus3panel, 59);
    lv_obj_set_y(ui_cus3panel, 10);
    lv_obj_set_align(ui_cus3panel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_cus3panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_cus3panel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_cus3panel, lv_color_hex(0xECE7D6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cus3panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_cus3panel, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_cus3panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_cus3panel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_cus3panel, LV_BORDER_SIDE_TOP, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cus3flourlab = lv_label_create(ui_cus3panel);
    lv_obj_set_width(ui_cus3flourlab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_cus3flourlab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_cus3flourlab, -128);
    lv_obj_set_y(ui_cus3flourlab, -100);
    lv_obj_set_align(ui_cus3flourlab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_cus3flourlab, "FLOUR                 :");
    lv_obj_set_style_text_font(ui_cus3flourlab, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cus3suglab = lv_label_create(ui_cus3panel);
    lv_obj_set_width(ui_cus3suglab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_cus3suglab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_cus3suglab, -128);
    lv_obj_set_y(ui_cus3suglab, 0);
    lv_obj_set_align(ui_cus3suglab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_cus3suglab, "SUGAR                 :");
    lv_obj_set_style_text_font(ui_cus3suglab, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cus3BPlab = lv_label_create(ui_cus3panel);
    lv_obj_set_width(ui_cus3BPlab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_cus3BPlab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_cus3BPlab, -155);
    lv_obj_set_y(ui_cus3BPlab, 100);
    lv_obj_set_align(ui_cus3BPlab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_cus3BPlab, "BAKING POWDER     :");
    lv_obj_set_style_text_font(ui_cus3BPlab, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cus3CPlab = lv_label_create(ui_cus3panel);
    lv_obj_set_width(ui_cus3CPlab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_cus3CPlab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_cus3CPlab, -155);
    lv_obj_set_y(ui_cus3CPlab, 200);
    lv_obj_set_align(ui_cus3CPlab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_cus3CPlab, "COCOA POWDER     :");
    lv_obj_set_style_text_font(ui_cus3CPlab, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_g_flour_cus3 = lv_label_create(ui_cus3panel);
    lv_obj_set_width(ui_g_flour_cus3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_g_flour_cus3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_g_flour_cus3, 212);
    lv_obj_set_y(ui_g_flour_cus3, -100);
    lv_obj_set_align(ui_g_flour_cus3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_g_flour_cus3, "g");

    ui_g_sug_cus3 = lv_label_create(ui_cus3panel);
    lv_obj_set_width(ui_g_sug_cus3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_g_sug_cus3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_g_sug_cus3, 212);
    lv_obj_set_y(ui_g_sug_cus3, 0);
    lv_obj_set_align(ui_g_sug_cus3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_g_sug_cus3, "g");

    ui_g_bp_cus3 = lv_label_create(ui_cus3panel);
    lv_obj_set_width(ui_g_bp_cus3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_g_bp_cus3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_g_bp_cus3, 212);
    lv_obj_set_y(ui_g_bp_cus3, 100);
    lv_obj_set_align(ui_g_bp_cus3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_g_bp_cus3, "g");

    ui_g_cp_cus3 = lv_label_create(ui_cus3panel);
    lv_obj_set_width(ui_g_cp_cus3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_g_cp_cus3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_g_cp_cus3, 212);
    lv_obj_set_y(ui_g_cp_cus3, 200);
    lv_obj_set_align(ui_g_cp_cus3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_g_cp_cus3, "g");

    ui_cus3nametext = lv_textarea_create(ui_cus3panel);
    lv_obj_set_width(ui_cus3nametext, 212);
    lv_obj_set_height(ui_cus3nametext, 42);
    lv_obj_set_x(ui_cus3nametext, 82);
    lv_obj_set_y(ui_cus3nametext, -200);
    lv_obj_set_align(ui_cus3nametext, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_cus3nametext, 10);
    lv_textarea_set_placeholder_text(ui_cus3nametext, "Enter name of recipe...");
    lv_obj_set_style_text_color(ui_cus3nametext, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_cus3nametext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_cus3nametext, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_cus3nametext, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_cus3nametext, lv_color_hex(0xFE5D5D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cus3nametext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_cus3nametext, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_cus3nametext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_cus3nametext, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_cus3nametext, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_cus3nametext, lv_color_hex(0x8C8C8C), LV_PART_MAIN | LV_STATE_EDITED);
    lv_obj_set_style_bg_opa(ui_cus3nametext, 255, LV_PART_MAIN | LV_STATE_EDITED);
    lv_obj_set_style_text_color(ui_cus3nametext, lv_color_hex(0x050505), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_cus3nametext, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_color(ui_cus3nametext, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_cus3nametext, 255, LV_PART_MAIN | LV_STATE_FOCUSED);


    lv_obj_set_style_text_color(ui_cus3nametext, lv_color_hex(0xFFFFFF), LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_cus3nametext, 255, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_cus3nametext, lv_color_hex(0x050505), LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_cus3nametext, 255, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_FOCUSED);

    ui_cus3namelab = lv_label_create(ui_cus3panel);
    lv_obj_set_width(ui_cus3namelab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_cus3namelab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_cus3namelab, -128);
    lv_obj_set_y(ui_cus3namelab, -200);
    lv_obj_set_align(ui_cus3namelab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_cus3namelab, "NAME                 :");
    lv_obj_set_style_text_font(ui_cus3namelab, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cus3flourtext = lv_textarea_create(ui_cus3panel);
    lv_obj_set_width(ui_cus3flourtext, 212);
    lv_obj_set_height(ui_cus3flourtext, 42);
    lv_obj_set_x(ui_cus3flourtext, 82);
    lv_obj_set_y(ui_cus3flourtext, -100);
    lv_obj_set_align(ui_cus3flourtext, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_cus3flourtext, 5);
    lv_textarea_set_text(ui_cus3flourtext, "375");
    lv_textarea_set_placeholder_text(ui_cus3flourtext, "Enter value in grams...");
    lv_obj_set_style_text_color(ui_cus3flourtext, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_cus3flourtext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_cus3flourtext, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_cus3flourtext, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_cus3flourtext, lv_color_hex(0xFE5D5D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cus3flourtext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_cus3flourtext, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_cus3flourtext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_cus3flourtext, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_cus3flourtext, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_cus3flourtext, lv_color_hex(0x8C8C8C), LV_PART_MAIN | LV_STATE_EDITED);
    lv_obj_set_style_bg_opa(ui_cus3flourtext, 255, LV_PART_MAIN | LV_STATE_EDITED);
    lv_obj_set_style_text_color(ui_cus3flourtext, lv_color_hex(0x050505), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_cus3flourtext, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_color(ui_cus3flourtext, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_cus3flourtext, 255, LV_PART_MAIN | LV_STATE_FOCUSED);


    lv_obj_set_style_text_color(ui_cus3flourtext, lv_color_hex(0x000000), LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_cus3flourtext, 255, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_cus3flourtext, lv_color_hex(0x050505), LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_cus3flourtext, 255, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_FOCUSED);

    ui_cus3sugtext = lv_textarea_create(ui_cus3panel);
    lv_obj_set_width(ui_cus3sugtext, 212);
    lv_obj_set_height(ui_cus3sugtext, 42);
    lv_obj_set_x(ui_cus3sugtext, 82);
    lv_obj_set_y(ui_cus3sugtext, 0);
    lv_obj_set_align(ui_cus3sugtext, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_cus3sugtext, 5);
    lv_textarea_set_text(ui_cus3sugtext, "375");
    lv_textarea_set_placeholder_text(ui_cus3sugtext, "Enter value in grams...");
    lv_obj_set_style_text_color(ui_cus3sugtext, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_cus3sugtext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_cus3sugtext, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_cus3sugtext, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_cus3sugtext, lv_color_hex(0xFE5D5D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cus3sugtext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_cus3sugtext, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_cus3sugtext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_cus3sugtext, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_cus3sugtext, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_cus3sugtext, lv_color_hex(0x8C8C8C), LV_PART_MAIN | LV_STATE_EDITED);
    lv_obj_set_style_bg_opa(ui_cus3sugtext, 255, LV_PART_MAIN | LV_STATE_EDITED);
    lv_obj_set_style_text_color(ui_cus3sugtext, lv_color_hex(0x050505), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_cus3sugtext, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_color(ui_cus3sugtext, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_cus3sugtext, 255, LV_PART_MAIN | LV_STATE_FOCUSED);


    lv_obj_set_style_text_color(ui_cus3sugtext, lv_color_hex(0x000000), LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_cus3sugtext, 255, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_cus3sugtext, lv_color_hex(0x050505), LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_cus3sugtext, 255, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_FOCUSED);

    ui_cus3BPtext = lv_textarea_create(ui_cus3panel);
    lv_obj_set_width(ui_cus3BPtext, 212);
    lv_obj_set_height(ui_cus3BPtext, 42);
    lv_obj_set_x(ui_cus3BPtext, 82);
    lv_obj_set_y(ui_cus3BPtext, 100);
    lv_obj_set_align(ui_cus3BPtext, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_cus3BPtext, 5);
    lv_textarea_set_text(ui_cus3BPtext, "375");
    lv_textarea_set_placeholder_text(ui_cus3BPtext, "Enter value in grams...");
    lv_obj_set_style_text_color(ui_cus3BPtext, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_cus3BPtext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_cus3BPtext, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_cus3BPtext, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_cus3BPtext, lv_color_hex(0xFE5D5D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cus3BPtext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_cus3BPtext, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_cus3BPtext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_cus3BPtext, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_cus3BPtext, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_cus3BPtext, lv_color_hex(0x8C8C8C), LV_PART_MAIN | LV_STATE_EDITED);
    lv_obj_set_style_bg_opa(ui_cus3BPtext, 255, LV_PART_MAIN | LV_STATE_EDITED);
    lv_obj_set_style_text_color(ui_cus3BPtext, lv_color_hex(0x050505), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_cus3BPtext, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_color(ui_cus3BPtext, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_cus3BPtext, 255, LV_PART_MAIN | LV_STATE_FOCUSED);


    lv_obj_set_style_text_color(ui_cus3BPtext, lv_color_hex(0x000000), LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_cus3BPtext, 255, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_cus3BPtext, lv_color_hex(0x050505), LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_cus3BPtext, 255, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_FOCUSED);

    ui_cus3CPtext = lv_textarea_create(ui_cus3panel);
    lv_obj_set_width(ui_cus3CPtext, 212);
    lv_obj_set_height(ui_cus3CPtext, 42);
    lv_obj_set_x(ui_cus3CPtext, 82);
    lv_obj_set_y(ui_cus3CPtext, 200);
    lv_obj_set_align(ui_cus3CPtext, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_cus3CPtext, 5);
    lv_textarea_set_text(ui_cus3CPtext, "375");
    lv_textarea_set_placeholder_text(ui_cus3CPtext, "Enter value in grams...");
    lv_obj_set_style_text_color(ui_cus3CPtext, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_cus3CPtext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_cus3CPtext, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_cus3CPtext, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_cus3CPtext, lv_color_hex(0xFE5D5D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cus3CPtext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_cus3CPtext, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_cus3CPtext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_cus3CPtext, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_cus3CPtext, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_cus3CPtext, lv_color_hex(0x8C8C8C), LV_PART_MAIN | LV_STATE_EDITED);
    lv_obj_set_style_bg_opa(ui_cus3CPtext, 255, LV_PART_MAIN | LV_STATE_EDITED);
    lv_obj_set_style_text_color(ui_cus3CPtext, lv_color_hex(0x050505), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_cus3CPtext, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_color(ui_cus3CPtext, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_cus3CPtext, 255, LV_PART_MAIN | LV_STATE_FOCUSED);


    lv_obj_set_style_text_color(ui_cus3CPtext, lv_color_hex(0x000000), LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_cus3CPtext, 255, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_cus3CPtext, lv_color_hex(0x050505), LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_cus3CPtext, 255, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_FOCUSED);

    ui_cus3confirm = lv_imgbtn_create(ui_custom3rep);
    lv_imgbtn_set_src(ui_cus3confirm, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_confirm_icon_png, NULL);
    lv_imgbtn_set_src(ui_cus3confirm, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_confirm_icon_png, NULL);
    lv_imgbtn_set_src(ui_cus3confirm, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_cus3confirm, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_cus3confirm, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_cus3confirm, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_height(ui_cus3confirm, 64);
    lv_obj_set_width(ui_cus3confirm, LV_SIZE_CONTENT);   /// -137
    lv_obj_set_x(ui_cus3confirm, -340);
    lv_obj_set_y(ui_cus3confirm, 150);
    lv_obj_set_align(ui_cus3confirm, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_cus3confirm, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_cus3confirm, lv_color_hex(0x36FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cus3confirm, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_cus3confirm, lv_color_hex(0x0F00FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_cus3confirm, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cus3keyboard_num = lv_keyboard_create(ui_custom3rep);
    lv_keyboard_set_mode(ui_cus3keyboard_num, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_width(ui_cus3keyboard_num, 673);
    lv_obj_set_height(ui_cus3keyboard_num, 221);
    lv_obj_set_x(ui_cus3keyboard_num, 55);
    lv_obj_set_y(ui_cus3keyboard_num, 97);
    lv_obj_set_align(ui_cus3keyboard_num, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_cus3keyboard_num, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_radius(ui_cus3keyboard_num, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_cus3keyboard_num, lv_color_hex(0x5C5C5C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cus3keyboard_num, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_cus3keyboard_num, 100, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_cus3keyboard_num, lv_color_hex(0xFE5D5D), LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cus3keyboard_num, 255, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_cus3keyboard_num, lv_color_hex(0x000000), LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_cus3keyboard_num, 255, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_cus3keyboard_num, 1, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_cus3keyboard_num, LV_BORDER_SIDE_FULL, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_cus3keyboard_num, lv_color_hex(0xFFFFFF), LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_cus3keyboard_num, 255, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_cus3keyboard_num, &lv_font_montserrat_20, LV_PART_ITEMS | LV_STATE_DEFAULT);

    ui_cus3keyboard_let = lv_keyboard_create(ui_custom3rep);
    lv_obj_set_width(ui_cus3keyboard_let, 673);
    lv_obj_set_height(ui_cus3keyboard_let, 221);
    lv_obj_set_x(ui_cus3keyboard_let, 55);
    lv_obj_set_y(ui_cus3keyboard_let, 97);
    lv_obj_set_align(ui_cus3keyboard_let, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_cus3keyboard_let, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_radius(ui_cus3keyboard_let, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_cus3keyboard_let, lv_color_hex(0x5C5C5C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cus3keyboard_let, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_cus3keyboard_let, 100, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_cus3keyboard_let, lv_color_hex(0xFE5D5D), LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cus3keyboard_let, 255, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_cus3keyboard_let, lv_color_hex(0x000000), LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_cus3keyboard_let, 255, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_cus3keyboard_let, 1, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_cus3keyboard_let, LV_BORDER_SIDE_FULL, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_cus3keyboard_let, lv_color_hex(0xFFFFFF), LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_cus3keyboard_let, 255, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_cus3keyboard_let, &lv_font_montserrat_20, LV_PART_ITEMS | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_cus3_recipe, ui_event_cus3_recipe, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_cus3_home, ui_event_cus3_home, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_cus3nametext, ui_event_cus3nametext, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_cus3flourtext, ui_event_cus3flourtext, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_cus3sugtext, ui_event_cus3sugtext, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_cus3BPtext, ui_event_cus3BPtext, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_cus3CPtext, ui_event_cus3CPtext, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_cus3confirm, ui_event_cus3confirm, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_custom3rep, ui_event_custom3rep, LV_EVENT_ALL, NULL);

}
