// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_cupcakesrep_screen_init(void)
{
    ui_cupcakesrep = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_cupcakesrep, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_cupcakesrep, lv_color_hex(0x454444), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cupcakesrep, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_cupcakesrep, lv_color_hex(0x6E6E6E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_cupcakesrep, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_cupcakesrep, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_cupcakesrep, LV_BORDER_SIDE_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cup_recipe = lv_imgbtn_create(ui_cupcakesrep);
    lv_imgbtn_set_src(ui_cup_recipe, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_kitchen_whisk_icon_png, NULL);
    lv_imgbtn_set_src(ui_cup_recipe, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_kitchen_whisk_icon_png, NULL);
    lv_imgbtn_set_src(ui_cup_recipe, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_cup_recipe, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_cup_recipe, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_cup_recipe, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_height(ui_cup_recipe, 72);
    lv_obj_set_width(ui_cup_recipe, LV_SIZE_CONTENT);   /// -137
    lv_obj_set_x(ui_cup_recipe, -340);
    lv_obj_set_y(ui_cup_recipe, -80);
    lv_obj_set_align(ui_cup_recipe, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_cup_recipe, lv_color_hex(0x6E6E6E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cup_recipe, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_cup_recipe, lv_color_hex(0x0F00FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_cup_recipe, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cup_home = lv_imgbtn_create(ui_cupcakesrep);
    lv_imgbtn_set_src(ui_cup_home, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_home_icon_png, NULL);
    lv_imgbtn_set_src(ui_cup_home, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_home_icon_png, NULL);
    lv_imgbtn_set_src(ui_cup_home, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_cup_home, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_cup_home, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_cup_home, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_height(ui_cup_home, 79);
    lv_obj_set_width(ui_cup_home, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_cup_home, -347);
    lv_obj_set_y(ui_cup_home, -191);
    lv_obj_set_align(ui_cup_home, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_cup_home, lv_color_hex(0x6E6E6E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cup_home, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cup_page = lv_imgbtn_create(ui_cupcakesrep);
    lv_imgbtn_set_src(ui_cup_page, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_cupcake_icon_png, NULL);
    lv_imgbtn_set_src(ui_cup_page, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_cupcake_icon_png, NULL);
    lv_imgbtn_set_src(ui_cup_page, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_cup_page, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_cup_page, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_cup_page, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_cup_page, 80);
    lv_obj_set_height(ui_cup_page, 74);
    lv_obj_set_x(ui_cup_page, -318);
    lv_obj_set_y(ui_cup_page, 25);
    lv_obj_set_align(ui_cup_page, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_cup_page, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_cup_page, lv_color_hex(0x8A00FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cup_page, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_cup_page, lv_color_hex(0x8A00FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_cup_page, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_cup_page, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_cup_page, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_cup_page, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_cup_page, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_cup_page, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_cup_page, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cupcakepanel = lv_obj_create(ui_cupcakesrep);
    lv_obj_set_width(ui_cupcakepanel, 696);
    lv_obj_set_height(ui_cupcakepanel, 482);
    lv_obj_set_x(ui_cupcakepanel, 59);
    lv_obj_set_y(ui_cupcakepanel, 9);
    lv_obj_set_align(ui_cupcakepanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_cupcakepanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_cupcakepanel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_cupcakepanel, lv_color_hex(0xECE7D6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cupcakepanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_cupcakepanel, lv_color_hex(0x8A00FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_cupcakepanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_cupcakepanel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_cupcakepanel, LV_BORDER_SIDE_TOP, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cupflourlab = lv_label_create(ui_cupcakepanel);
    lv_obj_set_width(ui_cupflourlab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_cupflourlab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_cupflourlab, -128);
    lv_obj_set_y(ui_cupflourlab, -150);
    lv_obj_set_align(ui_cupflourlab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_cupflourlab, "FLOUR                 :");
    lv_obj_set_style_text_font(ui_cupflourlab, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cupflourtext = lv_textarea_create(ui_cupcakepanel);
    lv_obj_set_width(ui_cupflourtext, 212);
    lv_obj_set_height(ui_cupflourtext, 42);
    lv_obj_set_x(ui_cupflourtext, 82);
    lv_obj_set_y(ui_cupflourtext, -150);
    lv_obj_set_align(ui_cupflourtext, LV_ALIGN_CENTER);
    if("0,1,2,3,4,5,6,7,8,9,." == "") lv_textarea_set_accepted_chars(ui_cupflourtext, NULL);
    else lv_textarea_set_accepted_chars(ui_cupflourtext, "0,1,2,3,4,5,6,7,8,9,.");
    lv_textarea_set_max_length(ui_cupflourtext, 5);
    lv_textarea_set_text(ui_cupflourtext, "375");
    lv_textarea_set_placeholder_text(ui_cupflourtext, "Enter value in grams...");
    lv_obj_set_style_text_color(ui_cupflourtext, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_cupflourtext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_cupflourtext, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_cupflourtext, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_cupflourtext, lv_color_hex(0xA841FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cupflourtext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_cupflourtext, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_cupflourtext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_cupflourtext, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_cupflourtext, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_cupflourtext, lv_color_hex(0x8C8C8C), LV_PART_MAIN | LV_STATE_EDITED);
    lv_obj_set_style_bg_opa(ui_cupflourtext, 255, LV_PART_MAIN | LV_STATE_EDITED);
    lv_obj_set_style_text_color(ui_cupflourtext, lv_color_hex(0x050505), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_cupflourtext, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_color(ui_cupflourtext, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_cupflourtext, 255, LV_PART_MAIN | LV_STATE_FOCUSED);


    lv_obj_set_style_text_color(ui_cupflourtext, lv_color_hex(0xFFFFFF), LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_cupflourtext, 255, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_cupflourtext, lv_color_hex(0x050505), LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_cupflourtext, 255, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_FOCUSED);

    ui_cupsuglab = lv_label_create(ui_cupcakepanel);
    lv_obj_set_width(ui_cupsuglab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_cupsuglab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_cupsuglab, -128);
    lv_obj_set_y(ui_cupsuglab, -50);
    lv_obj_set_align(ui_cupsuglab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_cupsuglab, "SUGAR                 :");
    lv_obj_set_style_text_font(ui_cupsuglab, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cupBPlab = lv_label_create(ui_cupcakepanel);
    lv_obj_set_width(ui_cupBPlab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_cupBPlab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_cupBPlab, -155);
    lv_obj_set_y(ui_cupBPlab, 50);
    lv_obj_set_align(ui_cupBPlab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_cupBPlab, "BAKING POWDER     :");
    lv_obj_set_style_text_font(ui_cupBPlab, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cupCPlab = lv_label_create(ui_cupcakepanel);
    lv_obj_set_width(ui_cupCPlab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_cupCPlab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_cupCPlab, -155);
    lv_obj_set_y(ui_cupCPlab, 150);
    lv_obj_set_align(ui_cupCPlab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_cupCPlab, "COCOA POWDER     :");
    lv_obj_set_style_text_font(ui_cupCPlab, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_g_flour_cup = lv_label_create(ui_cupcakepanel);
    lv_obj_set_width(ui_g_flour_cup, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_g_flour_cup, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_g_flour_cup, 212);
    lv_obj_set_y(ui_g_flour_cup, -150);
    lv_obj_set_align(ui_g_flour_cup, LV_ALIGN_CENTER);
    lv_label_set_text(ui_g_flour_cup, "g");

    ui_g_sug_cup = lv_label_create(ui_cupcakepanel);
    lv_obj_set_width(ui_g_sug_cup, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_g_sug_cup, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_g_sug_cup, 212);
    lv_obj_set_y(ui_g_sug_cup, -50);
    lv_obj_set_align(ui_g_sug_cup, LV_ALIGN_CENTER);
    lv_label_set_text(ui_g_sug_cup, "g");

    ui_g_bp_cup = lv_label_create(ui_cupcakepanel);
    lv_obj_set_width(ui_g_bp_cup, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_g_bp_cup, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_g_bp_cup, 212);
    lv_obj_set_y(ui_g_bp_cup, 50);
    lv_obj_set_align(ui_g_bp_cup, LV_ALIGN_CENTER);
    lv_label_set_text(ui_g_bp_cup, "g");

    ui_g_cp_cup = lv_label_create(ui_cupcakepanel);
    lv_obj_set_width(ui_g_cp_cup, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_g_cp_cup, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_g_cp_cup, 212);
    lv_obj_set_y(ui_g_cp_cup, 150);
    lv_obj_set_align(ui_g_cp_cup, LV_ALIGN_CENTER);
    lv_label_set_text(ui_g_cp_cup, "g");

    ui_Panel4 = lv_obj_create(ui_cupcakepanel);
    lv_obj_set_width(ui_Panel4, 62);
    lv_obj_set_height(ui_Panel4, 217);
    lv_obj_set_x(ui_Panel4, -213);
    lv_obj_set_y(ui_Panel4, -176);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0x8C8C8C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel4, lv_color_hex(0x8A00FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel4, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_angle(ui_Panel4, 450, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label13 = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label13, 43);
    lv_obj_set_y(ui_Label13, 63);
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "Cup Cakes");
    lv_obj_set_style_text_color(ui_Label13, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label13, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_angle(ui_Label13, -900, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cupsugtext = lv_textarea_create(ui_cupcakepanel);
    lv_obj_set_width(ui_cupsugtext, 212);
    lv_obj_set_height(ui_cupsugtext, 42);
    lv_obj_set_x(ui_cupsugtext, 82);
    lv_obj_set_y(ui_cupsugtext, -50);
    lv_obj_set_align(ui_cupsugtext, LV_ALIGN_CENTER);
    if("0,1,2,3,4,5,6,7,8,9,." == "") lv_textarea_set_accepted_chars(ui_cupsugtext, NULL);
    else lv_textarea_set_accepted_chars(ui_cupsugtext, "0,1,2,3,4,5,6,7,8,9,.");
    lv_textarea_set_max_length(ui_cupsugtext, 5);
    lv_textarea_set_text(ui_cupsugtext, "375");
    lv_textarea_set_placeholder_text(ui_cupsugtext, "Enter value in grams...");
    lv_obj_set_style_text_color(ui_cupsugtext, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_cupsugtext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_cupsugtext, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_cupsugtext, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_cupsugtext, lv_color_hex(0xA841FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cupsugtext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_cupsugtext, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_cupsugtext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_cupsugtext, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_cupsugtext, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_cupsugtext, lv_color_hex(0x8C8C8C), LV_PART_MAIN | LV_STATE_EDITED);
    lv_obj_set_style_bg_opa(ui_cupsugtext, 255, LV_PART_MAIN | LV_STATE_EDITED);
    lv_obj_set_style_text_color(ui_cupsugtext, lv_color_hex(0x050505), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_cupsugtext, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_color(ui_cupsugtext, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_cupsugtext, 255, LV_PART_MAIN | LV_STATE_FOCUSED);


    lv_obj_set_style_text_color(ui_cupsugtext, lv_color_hex(0xFFFFFF), LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_cupsugtext, 255, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_cupsugtext, lv_color_hex(0x050505), LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_cupsugtext, 255, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_FOCUSED);

    ui_cupBPtext = lv_textarea_create(ui_cupcakepanel);
    lv_obj_set_width(ui_cupBPtext, 212);
    lv_obj_set_height(ui_cupBPtext, 42);
    lv_obj_set_x(ui_cupBPtext, 82);
    lv_obj_set_y(ui_cupBPtext, 50);
    lv_obj_set_align(ui_cupBPtext, LV_ALIGN_CENTER);
    if("0,1,2,3,4,5,6,7,8,9,." == "") lv_textarea_set_accepted_chars(ui_cupBPtext, NULL);
    else lv_textarea_set_accepted_chars(ui_cupBPtext, "0,1,2,3,4,5,6,7,8,9,.");
    lv_textarea_set_max_length(ui_cupBPtext, 5);
    lv_textarea_set_text(ui_cupBPtext, "375");
    lv_textarea_set_placeholder_text(ui_cupBPtext, "Enter value in grams...");
    lv_obj_set_style_text_color(ui_cupBPtext, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_cupBPtext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_cupBPtext, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_cupBPtext, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_cupBPtext, lv_color_hex(0xA841FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cupBPtext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_cupBPtext, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_cupBPtext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_cupBPtext, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_cupBPtext, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_cupBPtext, lv_color_hex(0x8C8C8C), LV_PART_MAIN | LV_STATE_EDITED);
    lv_obj_set_style_bg_opa(ui_cupBPtext, 255, LV_PART_MAIN | LV_STATE_EDITED);
    lv_obj_set_style_text_color(ui_cupBPtext, lv_color_hex(0x050505), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_cupBPtext, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_color(ui_cupBPtext, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_cupBPtext, 255, LV_PART_MAIN | LV_STATE_FOCUSED);


    lv_obj_set_style_text_color(ui_cupBPtext, lv_color_hex(0xFFFFFF), LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_cupBPtext, 255, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_cupBPtext, lv_color_hex(0x050505), LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_cupBPtext, 255, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_FOCUSED);

    ui_cupCPtext = lv_textarea_create(ui_cupcakepanel);
    lv_obj_set_width(ui_cupCPtext, 212);
    lv_obj_set_height(ui_cupCPtext, 42);
    lv_obj_set_x(ui_cupCPtext, 82);
    lv_obj_set_y(ui_cupCPtext, 150);
    lv_obj_set_align(ui_cupCPtext, LV_ALIGN_CENTER);
    if("0,1,2,3,4,5,6,7,8,9,." == "") lv_textarea_set_accepted_chars(ui_cupCPtext, NULL);
    else lv_textarea_set_accepted_chars(ui_cupCPtext, "0,1,2,3,4,5,6,7,8,9,.");
    lv_textarea_set_max_length(ui_cupCPtext, 5);
    lv_textarea_set_text(ui_cupCPtext, "375");
    lv_textarea_set_placeholder_text(ui_cupCPtext, "Enter value in grams...");
    lv_obj_set_style_text_color(ui_cupCPtext, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_cupCPtext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_cupCPtext, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_cupCPtext, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_cupCPtext, lv_color_hex(0xA841FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cupCPtext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_cupCPtext, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_cupCPtext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_cupCPtext, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_cupCPtext, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_cupCPtext, lv_color_hex(0x8C8C8C), LV_PART_MAIN | LV_STATE_EDITED);
    lv_obj_set_style_bg_opa(ui_cupCPtext, 255, LV_PART_MAIN | LV_STATE_EDITED);
    lv_obj_set_style_text_color(ui_cupCPtext, lv_color_hex(0x050505), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_cupCPtext, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_color(ui_cupCPtext, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_cupCPtext, 255, LV_PART_MAIN | LV_STATE_FOCUSED);


    lv_obj_set_style_text_color(ui_cupCPtext, lv_color_hex(0xFFFFFF), LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_cupCPtext, 255, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_cupCPtext, lv_color_hex(0x050505), LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_cupCPtext, 255, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_FOCUSED);

    ui_cupconfirm = lv_imgbtn_create(ui_cupcakesrep);
    lv_imgbtn_set_src(ui_cupconfirm, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_confirm_icon_png, NULL);
    lv_imgbtn_set_src(ui_cupconfirm, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_confirm_icon_png, NULL);
    lv_imgbtn_set_src(ui_cupconfirm, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_cupconfirm, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_cupconfirm, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_cupconfirm, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_height(ui_cupconfirm, 64);
    lv_obj_set_width(ui_cupconfirm, LV_SIZE_CONTENT);   /// -137
    lv_obj_set_x(ui_cupconfirm, -340);
    lv_obj_set_y(ui_cupconfirm, 150);
    lv_obj_set_align(ui_cupconfirm, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_cupconfirm, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_cupconfirm, lv_color_hex(0x36FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cupconfirm, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_cupconfirm, lv_color_hex(0x0F00FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_cupconfirm, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cupkeyboard1 = lv_keyboard_create(ui_cupcakesrep);
    lv_keyboard_set_mode(ui_cupkeyboard1, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_width(ui_cupkeyboard1, 673);
    lv_obj_set_height(ui_cupkeyboard1, 228);
    lv_obj_set_x(ui_cupkeyboard1, 55);
    lv_obj_set_y(ui_cupkeyboard1, 97);
    lv_obj_set_align(ui_cupkeyboard1, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_cupkeyboard1, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_radius(ui_cupkeyboard1, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_cupkeyboard1, lv_color_hex(0x5C5C5C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cupkeyboard1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_cupkeyboard1, 100, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_cupkeyboard1, lv_color_hex(0xA841FF), LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cupkeyboard1, 255, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_cupkeyboard1, lv_color_hex(0x000000), LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_cupkeyboard1, 255, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_cupkeyboard1, 1, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_cupkeyboard1, LV_BORDER_SIDE_FULL, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_cupkeyboard1, lv_color_hex(0xFFFFFF), LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_cupkeyboard1, 255, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_cupkeyboard1, &lv_font_montserrat_20, LV_PART_ITEMS | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_cup_recipe, ui_event_cup_recipe, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_cup_home, ui_event_cup_home, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_cupflourtext, ui_event_cupflourtext, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_cupsugtext, ui_event_cupsugtext, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_cupBPtext, ui_event_cupBPtext, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_cupCPtext, ui_event_cupCPtext, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_cupconfirm, ui_event_cupconfirm, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_cupkeyboard1, ui_cupflourtext);
    lv_obj_add_event_cb(ui_cupcakesrep, ui_event_cupcakesrep, LV_EVENT_ALL, NULL);

}
