// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_custom2rep_screen_init(void)
{
    ui_custom2rep = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_custom2rep, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_custom2rep, lv_color_hex(0x454444), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_custom2rep, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_custom2rep, lv_color_hex(0x6E6E6E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_custom2rep, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_custom2rep, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_custom2rep, LV_BORDER_SIDE_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cus2_recipe = lv_imgbtn_create(ui_custom2rep);
    lv_imgbtn_set_src(ui_cus2_recipe, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_kitchen_whisk_icon_png, NULL);
    lv_imgbtn_set_src(ui_cus2_recipe, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_kitchen_whisk_icon_png, NULL);
    lv_imgbtn_set_src(ui_cus2_recipe, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_cus2_recipe, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_cus2_recipe, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_cus2_recipe, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_height(ui_cus2_recipe, 72);
    lv_obj_set_width(ui_cus2_recipe, LV_SIZE_CONTENT);   /// -137
    lv_obj_set_x(ui_cus2_recipe, -340);
    lv_obj_set_y(ui_cus2_recipe, -80);
    lv_obj_set_align(ui_cus2_recipe, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_cus2_recipe, lv_color_hex(0x6E6E6E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cus2_recipe, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_cus2_recipe, lv_color_hex(0x0F00FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_cus2_recipe, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cus2_home = lv_imgbtn_create(ui_custom2rep);
    lv_imgbtn_set_src(ui_cus2_home, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_home_icon_png, NULL);
    lv_imgbtn_set_src(ui_cus2_home, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_home_icon_png, NULL);
    lv_imgbtn_set_src(ui_cus2_home, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_cus2_home, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_cus2_home, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_cus2_home, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_height(ui_cus2_home, 79);
    lv_obj_set_width(ui_cus2_home, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_cus2_home, -347);
    lv_obj_set_y(ui_cus2_home, -191);
    lv_obj_set_align(ui_cus2_home, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_cus2_home, lv_color_hex(0x6E6E6E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cus2_home, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cus2_page = lv_imgbtn_create(ui_custom2rep);
    lv_imgbtn_set_src(ui_cus2_page, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_add_circle_png, NULL);
    lv_imgbtn_set_src(ui_cus2_page, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_add_circle_png, NULL);
    lv_imgbtn_set_src(ui_cus2_page, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_cus2_page, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_cus2_page, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_cus2_page, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_cus2_page, 80);
    lv_obj_set_height(ui_cus2_page, 73);
    lv_obj_set_x(ui_cus2_page, -318);
    lv_obj_set_y(ui_cus2_page, 25);
    lv_obj_set_align(ui_cus2_page, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_cus2_page, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_cus2_page, lv_color_hex(0xFF006B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cus2_page, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_cus2_page, lv_color_hex(0xFF006B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_cus2_page, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_cus2_page, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_cus2_page, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_cus2_page, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_cus2_page, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_cus2_page, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_cus2_page, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cus2panel = lv_obj_create(ui_custom2rep);
    lv_obj_set_width(ui_cus2panel, 696);
    lv_obj_set_height(ui_cus2panel, 482);
    lv_obj_set_x(ui_cus2panel, 59);
    lv_obj_set_y(ui_cus2panel, 10);
    lv_obj_set_align(ui_cus2panel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_cus2panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_cus2panel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_cus2panel, lv_color_hex(0xECE7D6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cus2panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_cus2panel, lv_color_hex(0xFF006B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_cus2panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_cus2panel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_cus2panel, LV_BORDER_SIDE_TOP, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cus2flourlab = lv_label_create(ui_cus2panel);
    lv_obj_set_width(ui_cus2flourlab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_cus2flourlab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_cus2flourlab, -128);
    lv_obj_set_y(ui_cus2flourlab, -100);
    lv_obj_set_align(ui_cus2flourlab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_cus2flourlab, "FLOUR                 :");
    lv_obj_set_style_text_font(ui_cus2flourlab, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cus2suglab = lv_label_create(ui_cus2panel);
    lv_obj_set_width(ui_cus2suglab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_cus2suglab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_cus2suglab, -128);
    lv_obj_set_y(ui_cus2suglab, 0);
    lv_obj_set_align(ui_cus2suglab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_cus2suglab, "SUGAR                 :");
    lv_obj_set_style_text_font(ui_cus2suglab, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cus2BPlab = lv_label_create(ui_cus2panel);
    lv_obj_set_width(ui_cus2BPlab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_cus2BPlab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_cus2BPlab, -155);
    lv_obj_set_y(ui_cus2BPlab, 100);
    lv_obj_set_align(ui_cus2BPlab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_cus2BPlab, "BAKING POWDER     :");
    lv_obj_set_style_text_font(ui_cus2BPlab, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cus2CPlab = lv_label_create(ui_cus2panel);
    lv_obj_set_width(ui_cus2CPlab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_cus2CPlab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_cus2CPlab, -155);
    lv_obj_set_y(ui_cus2CPlab, 200);
    lv_obj_set_align(ui_cus2CPlab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_cus2CPlab, "COCOA POWDER     :");
    lv_obj_set_style_text_font(ui_cus2CPlab, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_g_flour_cus2 = lv_label_create(ui_cus2panel);
    lv_obj_set_width(ui_g_flour_cus2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_g_flour_cus2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_g_flour_cus2, 212);
    lv_obj_set_y(ui_g_flour_cus2, -100);
    lv_obj_set_align(ui_g_flour_cus2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_g_flour_cus2, "g");

    ui_g_sug_cus2 = lv_label_create(ui_cus2panel);
    lv_obj_set_width(ui_g_sug_cus2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_g_sug_cus2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_g_sug_cus2, 212);
    lv_obj_set_y(ui_g_sug_cus2, 0);
    lv_obj_set_align(ui_g_sug_cus2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_g_sug_cus2, "g");

    ui_g_bp_cus2 = lv_label_create(ui_cus2panel);
    lv_obj_set_width(ui_g_bp_cus2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_g_bp_cus2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_g_bp_cus2, 212);
    lv_obj_set_y(ui_g_bp_cus2, 100);
    lv_obj_set_align(ui_g_bp_cus2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_g_bp_cus2, "g");

    ui_g_cp_cus2 = lv_label_create(ui_cus2panel);
    lv_obj_set_width(ui_g_cp_cus2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_g_cp_cus2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_g_cp_cus2, 212);
    lv_obj_set_y(ui_g_cp_cus2, 200);
    lv_obj_set_align(ui_g_cp_cus2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_g_cp_cus2, "g");

    ui_cus2nametext = lv_textarea_create(ui_cus2panel);
    lv_obj_set_width(ui_cus2nametext, 212);
    lv_obj_set_height(ui_cus2nametext, 42);
    lv_obj_set_x(ui_cus2nametext, 82);
    lv_obj_set_y(ui_cus2nametext, -200);
    lv_obj_set_align(ui_cus2nametext, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_cus2nametext, 10);
    lv_textarea_set_placeholder_text(ui_cus2nametext, "Enter name of recipe...");
    lv_obj_set_style_text_color(ui_cus2nametext, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_cus2nametext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_cus2nametext, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_cus2nametext, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_cus2nametext, lv_color_hex(0xFD5198), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cus2nametext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_cus2nametext, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_cus2nametext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_cus2nametext, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_cus2nametext, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_cus2nametext, lv_color_hex(0x8C8C8C), LV_PART_MAIN | LV_STATE_EDITED);
    lv_obj_set_style_bg_opa(ui_cus2nametext, 255, LV_PART_MAIN | LV_STATE_EDITED);
    lv_obj_set_style_text_color(ui_cus2nametext, lv_color_hex(0x050505), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_cus2nametext, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_color(ui_cus2nametext, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_cus2nametext, 255, LV_PART_MAIN | LV_STATE_FOCUSED);


    lv_obj_set_style_text_color(ui_cus2nametext, lv_color_hex(0xFFFFFF), LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_cus2nametext, 255, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_cus2nametext, lv_color_hex(0x050505), LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_cus2nametext, 255, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_FOCUSED);

    ui_cus2namelab = lv_label_create(ui_cus2panel);
    lv_obj_set_width(ui_cus2namelab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_cus2namelab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_cus2namelab, -128);
    lv_obj_set_y(ui_cus2namelab, -200);
    lv_obj_set_align(ui_cus2namelab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_cus2namelab, "NAME                 :");
    lv_obj_set_style_text_font(ui_cus2namelab, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cus2flourtext = lv_textarea_create(ui_cus2panel);
    lv_obj_set_width(ui_cus2flourtext, 212);
    lv_obj_set_height(ui_cus2flourtext, 42);
    lv_obj_set_x(ui_cus2flourtext, 82);
    lv_obj_set_y(ui_cus2flourtext, -100);
    lv_obj_set_align(ui_cus2flourtext, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_cus2flourtext, 5);
    lv_textarea_set_text(ui_cus2flourtext, "375");
    lv_textarea_set_placeholder_text(ui_cus2flourtext, "Enter value in grams...");
    lv_obj_set_style_text_color(ui_cus2flourtext, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_cus2flourtext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_cus2flourtext, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_cus2flourtext, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_cus2flourtext, lv_color_hex(0xFD5198), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cus2flourtext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_cus2flourtext, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_cus2flourtext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_cus2flourtext, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_cus2flourtext, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_cus2flourtext, lv_color_hex(0x8C8C8C), LV_PART_MAIN | LV_STATE_EDITED);
    lv_obj_set_style_bg_opa(ui_cus2flourtext, 255, LV_PART_MAIN | LV_STATE_EDITED);
    lv_obj_set_style_text_color(ui_cus2flourtext, lv_color_hex(0x050505), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_cus2flourtext, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_color(ui_cus2flourtext, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_cus2flourtext, 255, LV_PART_MAIN | LV_STATE_FOCUSED);


    lv_obj_set_style_text_color(ui_cus2flourtext, lv_color_hex(0x000000), LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_cus2flourtext, 255, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_cus2flourtext, lv_color_hex(0x050505), LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_cus2flourtext, 255, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_FOCUSED);

    ui_cus2sugtext = lv_textarea_create(ui_cus2panel);
    lv_obj_set_width(ui_cus2sugtext, 212);
    lv_obj_set_height(ui_cus2sugtext, 42);
    lv_obj_set_x(ui_cus2sugtext, 82);
    lv_obj_set_y(ui_cus2sugtext, 0);
    lv_obj_set_align(ui_cus2sugtext, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_cus2sugtext, 5);
    lv_textarea_set_text(ui_cus2sugtext, "375");
    lv_textarea_set_placeholder_text(ui_cus2sugtext, "Enter value in grams...");
    lv_obj_set_style_text_color(ui_cus2sugtext, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_cus2sugtext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_cus2sugtext, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_cus2sugtext, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_cus2sugtext, lv_color_hex(0xFD5198), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cus2sugtext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_cus2sugtext, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_cus2sugtext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_cus2sugtext, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_cus2sugtext, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_cus2sugtext, lv_color_hex(0x8C8C8C), LV_PART_MAIN | LV_STATE_EDITED);
    lv_obj_set_style_bg_opa(ui_cus2sugtext, 255, LV_PART_MAIN | LV_STATE_EDITED);
    lv_obj_set_style_text_color(ui_cus2sugtext, lv_color_hex(0x050505), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_cus2sugtext, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_color(ui_cus2sugtext, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_cus2sugtext, 255, LV_PART_MAIN | LV_STATE_FOCUSED);


    lv_obj_set_style_text_color(ui_cus2sugtext, lv_color_hex(0x000000), LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_cus2sugtext, 255, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_cus2sugtext, lv_color_hex(0x050505), LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_cus2sugtext, 255, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_FOCUSED);

    ui_cus2BPtext = lv_textarea_create(ui_cus2panel);
    lv_obj_set_width(ui_cus2BPtext, 212);
    lv_obj_set_height(ui_cus2BPtext, 42);
    lv_obj_set_x(ui_cus2BPtext, 82);
    lv_obj_set_y(ui_cus2BPtext, 100);
    lv_obj_set_align(ui_cus2BPtext, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_cus2BPtext, 5);
    lv_textarea_set_text(ui_cus2BPtext, "375");
    lv_textarea_set_placeholder_text(ui_cus2BPtext, "Enter value in grams...");
    lv_obj_set_style_text_color(ui_cus2BPtext, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_cus2BPtext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_cus2BPtext, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_cus2BPtext, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_cus2BPtext, lv_color_hex(0xFD5198), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cus2BPtext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_cus2BPtext, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_cus2BPtext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_cus2BPtext, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_cus2BPtext, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_cus2BPtext, lv_color_hex(0x8C8C8C), LV_PART_MAIN | LV_STATE_EDITED);
    lv_obj_set_style_bg_opa(ui_cus2BPtext, 255, LV_PART_MAIN | LV_STATE_EDITED);
    lv_obj_set_style_text_color(ui_cus2BPtext, lv_color_hex(0x050505), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_cus2BPtext, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_color(ui_cus2BPtext, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_cus2BPtext, 255, LV_PART_MAIN | LV_STATE_FOCUSED);


    lv_obj_set_style_text_color(ui_cus2BPtext, lv_color_hex(0x000000), LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_cus2BPtext, 255, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_cus2BPtext, lv_color_hex(0x050505), LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_cus2BPtext, 255, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_FOCUSED);

    ui_cus2CPtext = lv_textarea_create(ui_cus2panel);
    lv_obj_set_width(ui_cus2CPtext, 212);
    lv_obj_set_height(ui_cus2CPtext, 42);
    lv_obj_set_x(ui_cus2CPtext, 82);
    lv_obj_set_y(ui_cus2CPtext, 200);
    lv_obj_set_align(ui_cus2CPtext, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_cus2CPtext, 5);
    lv_textarea_set_text(ui_cus2CPtext, "375");
    lv_textarea_set_placeholder_text(ui_cus2CPtext, "Enter value in grams...");
    lv_obj_set_style_text_color(ui_cus2CPtext, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_cus2CPtext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_cus2CPtext, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_cus2CPtext, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_cus2CPtext, lv_color_hex(0xFD5198), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cus2CPtext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_cus2CPtext, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_cus2CPtext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_cus2CPtext, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_cus2CPtext, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_cus2CPtext, lv_color_hex(0x8C8C8C), LV_PART_MAIN | LV_STATE_EDITED);
    lv_obj_set_style_bg_opa(ui_cus2CPtext, 255, LV_PART_MAIN | LV_STATE_EDITED);
    lv_obj_set_style_text_color(ui_cus2CPtext, lv_color_hex(0x050505), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_cus2CPtext, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_color(ui_cus2CPtext, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_cus2CPtext, 255, LV_PART_MAIN | LV_STATE_FOCUSED);


    lv_obj_set_style_text_color(ui_cus2CPtext, lv_color_hex(0x000000), LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_cus2CPtext, 255, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_cus2CPtext, lv_color_hex(0x050505), LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_cus2CPtext, 255, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_FOCUSED);

    ui_cus2confirm1 = lv_imgbtn_create(ui_custom2rep);
    lv_imgbtn_set_src(ui_cus2confirm1, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_confirm_icon_png, NULL);
    lv_imgbtn_set_src(ui_cus2confirm1, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_confirm_icon_png, NULL);
    lv_imgbtn_set_src(ui_cus2confirm1, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_cus2confirm1, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_cus2confirm1, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_cus2confirm1, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_height(ui_cus2confirm1, 64);
    lv_obj_set_width(ui_cus2confirm1, LV_SIZE_CONTENT);   /// -137
    lv_obj_set_x(ui_cus2confirm1, -340);
    lv_obj_set_y(ui_cus2confirm1, 150);
    lv_obj_set_align(ui_cus2confirm1, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_cus2confirm1, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_cus2confirm1, lv_color_hex(0x36FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cus2confirm1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_cus2confirm1, lv_color_hex(0x0F00FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_cus2confirm1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cus2keyboard_num = lv_keyboard_create(ui_custom2rep);
    lv_keyboard_set_mode(ui_cus2keyboard_num, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_width(ui_cus2keyboard_num, 673);
    lv_obj_set_height(ui_cus2keyboard_num, 221);
    lv_obj_set_x(ui_cus2keyboard_num, 55);
    lv_obj_set_y(ui_cus2keyboard_num, 97);
    lv_obj_set_align(ui_cus2keyboard_num, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_cus2keyboard_num, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_radius(ui_cus2keyboard_num, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_cus2keyboard_num, lv_color_hex(0x5C5C5C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cus2keyboard_num, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_cus2keyboard_num, 100, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_cus2keyboard_num, lv_color_hex(0xFD5198), LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cus2keyboard_num, 255, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_cus2keyboard_num, lv_color_hex(0x000000), LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_cus2keyboard_num, 255, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_cus2keyboard_num, 1, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_cus2keyboard_num, LV_BORDER_SIDE_FULL, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_cus2keyboard_num, &lv_font_montserrat_20, LV_PART_ITEMS | LV_STATE_DEFAULT);

    ui_cus2keyboard_let = lv_keyboard_create(ui_custom2rep);
    lv_obj_set_width(ui_cus2keyboard_let, 673);
    lv_obj_set_height(ui_cus2keyboard_let, 221);
    lv_obj_set_x(ui_cus2keyboard_let, 55);
    lv_obj_set_y(ui_cus2keyboard_let, 97);
    lv_obj_set_align(ui_cus2keyboard_let, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_cus2keyboard_let, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_radius(ui_cus2keyboard_let, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_cus2keyboard_let, lv_color_hex(0x5C5C5C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cus2keyboard_let, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_cus2keyboard_let, 100, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_cus2keyboard_let, lv_color_hex(0xFD5198), LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cus2keyboard_let, 255, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_cus2keyboard_let, lv_color_hex(0x000000), LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_cus2keyboard_let, 255, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_cus2keyboard_let, 1, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_cus2keyboard_let, LV_BORDER_SIDE_FULL, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_cus2keyboard_let, lv_color_hex(0xFFFFFF), LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_cus2keyboard_let, 255, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_cus2keyboard_let, &lv_font_montserrat_20, LV_PART_ITEMS | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_cus2_recipe, ui_event_cus2_recipe, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_cus2_home, ui_event_cus2_home, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_cus2nametext, ui_event_cus2nametext, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_cus2flourtext, ui_event_cus2flourtext, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_cus2sugtext, ui_event_cus2sugtext, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_cus2BPtext, ui_event_cus2BPtext, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_cus2CPtext, ui_event_cus2CPtext, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_cus2confirm1, ui_event_cus2confirm1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_custom2rep, ui_event_custom2rep, LV_EVENT_ALL, NULL);

}
